'use strict';
const MODE=(process.env.AI_MODE||'demo').toLowerCase();
const SYSTEM=`You are HealTrip's patient-language layer. You are not a doctor and must not diagnose, prescribe, invent tests, providers, statistics, or facts. Use only supplied structured facts and evidence. Say that possibilities are not diagnoses. Never reduce an emergency/urgent level. Do not reveal hidden reasoning. Keep responses concise and in the requested language.`;
async function callOpenAI(messages){const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',temperature:0.1,max_tokens:500,messages})});if(!r.ok)throw new Error(`openai ${r.status}`);const d=await r.json();return d.choices?.[0]?.message?.content?.trim()||'';}
async function callGemini(messages){const model=process.env.GEMINI_MODEL||'gemini-3.6-flash';const contents=messages.filter(x=>x.role!=='system').map(x=>({role:x.role==='assistant'?'model':'user',parts:[{text:x.content}]}));const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':process.env.GEMINI_API_KEY},body:JSON.stringify({system_instruction:{parts:[{text:SYSTEM}]},contents,generationConfig:{temperature:0.1,maxOutputTokens:500}})});if(!r.ok)throw new Error(`gemini ${r.status}`);const d=await r.json();return d.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').trim()||'';}
function deterministic(p,lang){const ar=lang==='ar';if(p.kind==='chat')return ar?'أستطيع مساعدتك في فهم المعلومات الموجودة في ملفك وتنظيمها أو شرح المصطلحات الطبية، لكنني لا أضع تشخيصًا أو أوصي بعلاج. إذا كان سؤالك عن أعراض جديدة، يمكنك بدء تقييم صحي مستقل.':'I can help explain and organize information in your health profile, but I do not diagnose or prescribe. If you have new symptoms, you can start a separate health assessment.';const names=(p.differential||[]).slice(0,3).map(x=>x.name);if(p.kind==='question')return ar?`${p.question}\n\nسبب السؤال: ${p.why}`:`${p.question}\n\nWhy this matters: ${p.why}`;if(!names.length)return ar?'لا توجد معلومات كافية بعد لبناء قائمة احتمالات مفيدة.':'There is not enough information yet to build a useful shortlist.';return ar?`بناءً على المعلومات التي ذكرتِها، توجد احتمالات متوافقة بدرجات مختلفة: ${names.join('، ')}. هذا ليس تشخيصًا. ${p.advice||''}`:`Based on what you reported, several possibilities have different levels of compatibility: ${names.join(', ')}. This is not a diagnosis. ${p.advice||''}`;}
function verify(text,payload,lang){if(!text)return {text:deterministic(payload,lang),verified:false,reason:'empty'};if(text.length>1800)return {text:deterministic(payload,lang),verified:false,reason:'length'};const banned=[/\byou have\b/i,/\bdiagnos(ed|is|e)?\b/i,/\bprescrib/i,/\bstart taking\b/i,/\bmg\b/i,/تشخيص/,/أنت مصاب/];if(banned.some(r=>r.test(text)))return {text:deterministic(payload,lang),verified:false,reason:'claim-screen'};return {text,verified:true,reason:'passed'};}
async function phrase(payload,lang='en'){if(MODE==='demo')return {text:deterministic(payload,lang),provider:'demo',verified:true,reason:'deterministic'};try{const msgs=[{role:'system',content:SYSTEM},{role:'user',content:`Language: ${lang}\nStructured input:\n${JSON.stringify(payload)}`}];const raw=MODE==='gemini'?await callGemini(msgs):await callOpenAI(msgs);const v=verify(raw,payload,lang);return {...v,provider:MODE};}catch(e){return {text:deterministic(payload,lang),provider:`${MODE}-fallback`,verified:false,reason:e.message};}}
async function chat({history,message,profile,lang}){const payload={kind:'chat',profile,question:message};if(MODE==='demo')return {text:deterministic(payload,lang),provider:'demo',verified:true};try{const safeHistory=(history||[]).slice(-12).map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content).slice(0,4000)}));const msgs=[{role:'system',content:SYSTEM+`\nPatient profile is supplied as structured context only. Do not invent missing medical facts. If asked for diagnosis or treatment, explain the limitation and suggest clinician evaluation rather than prescribing.`},{role:'user',content:`Profile: ${JSON.stringify(profile||{})}`} ,...safeHistory,{role:'user',content:message}];const raw=MODE==='gemini'?await callGemini(msgs):await callOpenAI(msgs);return {...verify(raw,payload,lang),provider:MODE};}catch(e){return {text:deterministic(payload,lang),provider:`${MODE}-fallback`,verified:false,reason:e.message};}}
module.exports={phrase,chat,MODE};
