const crypto=require('crypto');
'use strict';
const { Pool } = require('pg');
const providers = require('./clinical/providers');
let pool=null, mode='memory';
const mem={sessions:new Map(), users:new Map(), profiles:new Map(), conversations:new Map(), messages:new Map(), records:new Map(), audits:[]};
async function init(){
  if(!process.env.DATABASE_URL){mode='memory';return;}
  try{pool=new Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||10),idleTimeoutMillis:30000});await pool.query('select 1');mode='postgres';}
  catch(e){console.warn(`PostgreSQL unavailable (${e.message}). Falling back to in-memory storage.`);pool=null;mode='memory';}
}
const kind=()=>mode;
const q=async(sql,args=[])=>pool.query(sql,args);
async function saveSession(id,state,lang,userId=null){if(!pool){mem.sessions.set(id,{state,lang,userId});return;}await q(`insert into assessments(id,user_id,lang,state,updated_at) values($1,$2,$3,$4,now()) on conflict(id) do update set state=excluded.state,lang=excluded.lang,user_id=excluded.user_id,updated_at=now()`,[id,userId,lang,state]);}
async function getSession(id){if(!pool)return mem.sessions.get(id)?.state||null;const r=await q('select state from assessments where id=$1',[id]);return r.rows[0]?.state||null;}
async function deleteSession(id){if(!pool){mem.sessions.delete(id);return;}await q('delete from assessments where id=$1',[id]);}
async function audit(e){if(!pool){mem.audits.push(e);if(mem.audits.length>5000)mem.audits.shift();return;}await q('insert into audit_events(event,user_id,session_id,detail) values($1,$2,$3,$4)',[e.event,e.user_id||null,e.session_id||null,e.detail||{}]);}
async function createUser(email,passwordHash,role='patient'){if(!pool){const id=crypto.randomUUID();mem.users.set(email,{id,email,passwordHash,role});return mem.users.get(email);}const r=await q('insert into users(email,password_hash,role) values($1,$2,$3) returning id,email,role',[email,passwordHash,role]);return r.rows[0];}
async function findUser(email){if(!pool)return mem.users.get(email)||null;const r=await q('select id,email,password_hash,role from users where lower(email)=lower($1)',[email]);return r.rows[0]||null;}
async function getProfile(userId){if(!pool)return mem.profiles.get(userId)||null;const r=await q('select * from patient_profiles where user_id=$1',[userId]);return r.rows[0]||null;}
async function upsertProfile(userId,data){if(!pool){const p={user_id:userId,...data,updated_at:new Date().toISOString()};mem.profiles.set(userId,p);return p;}const r=await q(`insert into patient_profiles(user_id,full_name,date_of_birth,sex,country,city,preferred_language,phone,emergency_contact,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,now()) on conflict(user_id) do update set full_name=excluded.full_name,date_of_birth=excluded.date_of_birth,sex=excluded.sex,country=excluded.country,city=excluded.city,preferred_language=excluded.preferred_language,phone=excluded.phone,emergency_contact=excluded.emergency_contact,updated_at=now() returning *`,[userId,data.full_name||null,data.date_of_birth||null,data.sex||null,data.country||null,data.city||null,data.preferred_language||'en',data.phone||null,data.emergency_contact||{}]);return r.rows[0];}
async function addRecord(userId,type,title,content,source='patient',verified=false){if(!pool){const rec={id:crypto.randomUUID(),user_id:userId,record_type:type,title,content,source,verified,recorded_at:new Date().toISOString()};const a=mem.records.get(userId)||[];a.unshift(rec);mem.records.set(userId,a);return rec;}const r=await q('insert into patient_records(user_id,record_type,title,content,source,verified) values($1,$2,$3,$4,$5,$6) returning *',[userId,type,title||null,content,source,verified]);return r.rows[0];}
async function listRecords(userId,type){if(!pool)return (mem.records.get(userId)||[]).filter(x=>!type||x.record_type===type);const r=await q('select * from patient_records where user_id=$1 and ($2::text is null or record_type=$2) order by recorded_at desc',[userId,type||null]);return r.rows;}
async function createConversation(userId,title){const id=crypto.randomUUID();if(!pool){const c={id,userId,title,createdAt:new Date().toISOString()};mem.conversations.set(id,c);mem.messages.set(id,[]);return c;}const r=await q('insert into conversations(user_id,title) values($1,$2) returning *',[userId,title||'HealTrip AI']);return r.rows[0];}
async function listConversations(userId){if(!pool)return [...mem.conversations.values()].filter(c=>c.userId===userId);const r=await q('select * from conversations where user_id=$1 order by updated_at desc',[userId]);return r.rows;}
async function addMessage(conversationId,role,content,provider=null,verified=null){if(!pool){const m={id:Date.now(),role,content,provider,verified,createdAt:new Date().toISOString()};(mem.messages.get(conversationId)||[]).push(m);return m;}const r=await q('insert into conversation_messages(conversation_id,role,content,provider,verified) values($1,$2,$3,$4,$5) returning *',[conversationId,role,content,provider,verified]);await q('update conversations set updated_at=now() where id=$1',[conversationId]);return r.rows[0];}
async function getMessages(conversationId){if(!pool)return mem.messages.get(conversationId)||[];const r=await q('select * from conversation_messages where conversation_id=$1 order by created_at',[conversationId]);return r.rows;}
async function searchDoctors(filters){if(!pool)return providers.searchDoctors(filters);const c=['1=1'],a=[];const add=(s,v)=>{a.push(v);c.push(s.replace('$n',`$${a.length}`));};if(filters.specialty)add('lower(specialty)=lower($n)',filters.specialty);if(filters.country)add('lower(country)=lower($n)',filters.country);if(filters.city)add('lower(city)=lower($n)',filters.city);if(filters.language)add('$n=any(languages)',filters.language);if(filters.telemedicine===true)c.push('telemedicine=true');return (await q(`select * from doctors where ${c.join(' and ')} order by full_name`,a)).rows;}
async function searchHospitals(filters){if(!pool)return providers.searchHospitals(filters);const c=['1=1'],a=[];const add=(s,v)=>{a.push(v);c.push(s.replace('$n',`$${a.length}`));};if(filters.specialty)add('$n=any(specialties)',filters.specialty);if(filters.country)add('lower(country)=lower($n)',filters.country);if(filters.city)add('lower(city)=lower($n)',filters.city);if(filters.emergency===true)c.push('emergency=true');return (await q(`select * from hospitals where ${c.join(' and ')} order by name`,a)).rows;}
async function addToolCall(userId,conversationId,name,args,result){if(!pool)return;if(pool)await q('insert into ai_tool_calls(user_id,conversation_id,tool_name,arguments,result_summary) values($1,$2,$3,$4,$5)',[userId,conversationId,name,args||{},result||{}]);}
module.exports={init,kind,saveSession,getSession,deleteSession,audit,createUser,findUser,getProfile,upsertProfile,addRecord,listRecords,createConversation,listConversations,addMessage,getMessages,searchDoctors,searchHospitals,addToolCall};
