'use strict';

/**
 * HealTrip clinical knowledge base.
 *
 * This is a structured, auditable knowledge layer. It is deliberately NOT a
 * diagnostic database. Every entry describes:
 *   - which reported features make a candidate explanation more or less compatible
 *   - which findings a clinician uses to distinguish candidates
 *   - which evaluations a clinician may consider
 *   - which published sources the explanation text is grounded in
 *
 * Nothing here establishes a diagnosis. Scores express "compatibility with the
 * information the person has reported", never probability of disease.
 */

// ---------------------------------------------------------------------------
// Evidence sources (public, citable, no redistribution of source text)
// ---------------------------------------------------------------------------
const SOURCES = {
  who_ai_health: {
    id: 'who_ai_health',
    title: 'Ethics and governance of artificial intelligence for health',
    publisher: 'World Health Organization',
    url: 'https://www.who.int/publications/i/item/9789240029200',
    type: 'guidance',
    tier: 1,
  },
  nice_chest_pain: {
    id: 'nice_chest_pain',
    title: 'Recent-onset chest pain of suspected cardiac origin (CG95)',
    publisher: 'NICE (UK)',
    url: 'https://www.nice.org.uk/guidance/cg95',
    type: 'clinical guideline',
    tier: 1,
  },
  nice_headache: {
    id: 'nice_headache',
    title: 'Headaches in over 12s: diagnosis and management (CG150)',
    publisher: 'NICE (UK)',
    url: 'https://www.nice.org.uk/guidance/cg150',
    type: 'clinical guideline',
    tier: 1,
  },
  nice_sepsis: {
    id: 'nice_sepsis',
    title: 'Suspected sepsis: recognition, diagnosis and early management (NG51)',
    publisher: 'NICE (UK)',
    url: 'https://www.nice.org.uk/guidance/ng51',
    type: 'clinical guideline',
    tier: 1,
  },
  nice_low_back: {
    id: 'nice_low_back',
    title: 'Low back pain and sciatica in over 16s (NG59)',
    publisher: 'NICE (UK)',
    url: 'https://www.nice.org.uk/guidance/ng59',
    type: 'clinical guideline',
    tier: 1,
  },
  cdc_stroke: {
    id: 'cdc_stroke',
    title: 'Stroke signs and symptoms',
    publisher: 'US Centers for Disease Control and Prevention',
    url: 'https://www.cdc.gov/stroke/signs-symptoms/',
    type: 'public health reference',
    tier: 1,
  },
  medlineplus: {
    id: 'medlineplus',
    title: 'MedlinePlus health topics',
    publisher: 'US National Library of Medicine',
    url: 'https://medlineplus.gov/',
    type: 'general medical reference',
    tier: 4,
  },
  nhs_conditions: {
    id: 'nhs_conditions',
    title: 'Health A to Z',
    publisher: 'NHS (UK)',
    url: 'https://www.nhs.uk/conditions/',
    type: 'general medical reference',
    tier: 3,
  },
  hl7_fhir: {
    id: 'hl7_fhir',
    title: 'FHIR R4 specification',
    publisher: 'HL7 International',
    url: 'https://hl7.org/fhir/R4/',
    type: 'interoperability standard',
    tier: 2,
  },
};

// ---------------------------------------------------------------------------
// Presenting complaints recognised from free text (EN + AR)
// ---------------------------------------------------------------------------
const SYMPTOMS = {
  chest_pain: {
    en: 'Chest pain or discomfort',
    ar: 'ألم أو انزعاج في الصدر',
    match: ['chest pain', 'chest discomfort', 'chest tight', 'chest feels heavy', 'heavy chest', 'heaviness in my chest', 'pressure in my chest', 'صدري تقيل', 'ثقل في الصدر', 'pain in my chest', 'ألم في الصدر', 'وجع في الصدر', 'ضيق في الصدر', 'الصدر'],
  },
  breathlessness: {
    en: 'Shortness of breath',
    ar: 'ضيق في التنفس',
    match: ['short of breath', 'shortness of breath', 'breathless', 'cant breathe', "can't breathe", 'ضيق نفس', 'ضيق في التنفس', 'صعوبة في التنفس'],
  },
  palpitations: {
    en: 'Palpitations',
    ar: 'خفقان',
    match: ['palpitation', 'heart racing', 'fast heartbeat', 'خفقان', 'ضربات القلب سريعة'],
  },
  headache: {
    en: 'Headache',
    ar: 'صداع',
    match: ['headache', 'head ache', 'head pain', 'migraine', 'صداع', 'ألم في الرأس', 'شقيقة'],
  },
  fever: {
    en: 'Fever',
    ar: 'حمى',
    match: ['fever', 'temperature', 'feverish', 'حمى', 'سخونة', 'حرارة'],
  },
  cough: {
    en: 'Cough',
    ar: 'سعال',
    match: ['cough', 'coughing', 'سعال', 'كحة'],
  },
  sore_throat: {
    en: 'Sore throat',
    ar: 'التهاب الحلق',
    match: ['sore throat', 'throat pain', 'التهاب الحلق', 'ألم في الحلق'],
  },
  abdominal_pain: {
    en: 'Abdominal pain',
    ar: 'ألم في البطن',
    match: ['abdominal pain', 'stomach pain', 'belly pain', 'tummy pain', 'ألم في البطن', 'وجع بطن', 'مغص'],
  },
  nausea: {
    en: 'Nausea or vomiting',
    ar: 'غثيان أو قيء',
    match: ['nausea', 'nauseous', 'vomit', 'throwing up', 'feel sick', 'feeling sick', 'sick to my stomach', 'غثيان', 'قيء', 'ترجيع', 'دوخه ولف'],
  },
  diarrhoea: {
    en: 'Diarrhoea',
    ar: 'إسهال',
    match: ['diarrhea', 'diarrhoea', 'loose stool', 'إسهال'],
  },
  dizziness: {
    en: 'Dizziness or light-headedness',
    ar: 'دوخة',
    match: ['dizzy', 'dizziness', 'light headed', 'lightheaded', 'vertigo', 'دوخة', 'دوار'],
  },
  back_pain: {
    en: 'Back pain',
    ar: 'ألم في الظهر',
    match: ['back pain', 'lower back', 'backache', 'ألم في الظهر', 'وجع الظهر'],
  },
  urinary: {
    en: 'Urinary symptoms',
    ar: 'أعراض بولية',
    match: ['burning when i pee', 'painful urination', 'urinary', 'peeing often', 'حرقان البول', 'ألم عند التبول', 'تبول متكرر'],
  },
  rash: {
    en: 'Skin rash',
    ar: 'طفح جلدي',
    match: ['rash', 'skin spots', 'hives', 'طفح', 'حساسية جلد', 'بقع جلدية'],
  },
  fatigue: {
    en: 'Fatigue',
    ar: 'إرهاق',
    match: ['fatigue', 'tired', 'exhausted', 'no energy', 'إرهاق', 'تعب', 'إعياء'],
  },
  wheeze: {
    en: 'Wheezing or chest tightness',
    ar: 'أزيز أو ضيق في الصدر',
    match: ['wheez', 'whistling when i breathe', 'chest tightness', 'أزيز', 'صفير في الصدر'],
  },
  leg_swelling: {
    en: 'Leg pain or swelling',
    ar: 'ألم أو تورم في الساق',
    match: ['calf pain', 'leg swelling', 'swollen leg', 'swollen calf', 'ألم في الساق', 'تورم الساق', 'انتفاخ الساق'],
  },
  eye_redness: {
    en: 'Red or painful eye',
    ar: 'احمرار أو ألم في العين',
    match: ['red eye', 'eye pain', 'sore eye', 'احمرار العين', 'ألم في العين'],
  },
  ear_pain: {
    en: 'Ear pain',
    ar: 'ألم في الأذن',
    match: ['ear pain', 'earache', 'ear ache', 'ألم في الأذن', 'وجع أذن'],
  },
  facial_pain: {
    en: 'Facial pressure or sinus pain',
    ar: 'ضغط في الوجه أو ألم الجيوب',
    match: ['facial pain', 'sinus pain', 'pressure in my face', 'blocked nose', 'ألم الجيوب', 'انسداد الأنف'],
  },
  thirst: {
    en: 'Excessive thirst or passing urine often',
    ar: 'عطش شديد أو تبول متكرر',
    match: ['very thirsty', 'always thirsty', 'drinking a lot', 'peeing all night', 'عطش شديد', 'أشرب كثير'],
  },
  weight_loss: {
    en: 'Unintended weight loss',
    ar: 'فقدان وزن غير مقصود',
    match: ['losing weight', 'lost weight without trying', 'فقدان وزن', 'نقص وزني'],
  },
  night_sweats: {
    en: 'Night sweats',
    ar: 'تعرق ليلي',
    match: ['night sweats', 'sweating at night', 'تعرق ليلي', 'أتعرق بالليل'],
  },
  vertigo_spin: {
    en: 'Spinning sensation',
    ar: 'إحساس بالدوران',
    match: ['room is spinning', 'spinning', 'vertigo', 'الدنيا تلف', 'دوار دوراني'],
  },
  skin_infection: {
    en: 'Hot, red, spreading skin',
    ar: 'جلد ساخن ومحمر ينتشر',
    match: ['red and hot skin', 'spreading redness', 'skin is hot', 'احمرار ينتشر', 'جلد ساخن'],
  },
  joint_pain: {
    en: 'Joint pain',
    ar: 'ألم في المفاصل',
    match: ['joint pain', 'knee pain', 'swollen joint', 'ألم المفاصل', 'ألم في الركبة'],
  },
  anxiety: {
    en: 'Anxiety or stress',
    ar: 'قلق أو توتر',
    match: ['anxiety', 'anxious', 'panic', 'stressed', 'قلق', 'توتر', 'نوبة هلع'],
  },
};

// ---------------------------------------------------------------------------
// Deterministic red-flag rules. These run BEFORE any reasoning or model call.
// ---------------------------------------------------------------------------
const RED_FLAGS = [
  {
    id: 'acute_coronary',
    level: 'emergency',
    en: 'Chest pain with breathlessness, sweating, or pain spreading to the arm, jaw or back',
    ar: 'ألم في الصدر مع ضيق نفس أو تعرق أو ألم ينتشر إلى الذراع أو الفك أو الظهر',
    concepts: [['chest','صدر','قلب'],['sweat','clammy','pale','breath','breathless','faint','collaps','تعرق','نفس','إغماء','شحوب']],
    match: ['crushing chest pain', 'chest pain and sweating', 'pain going down my arm', 'pain radiating to my arm', 'chest pain radiating', 'ألم ينتشر للذراع', 'ألم الصدر مع تعرق', 'ألم ضاغط في الصدر'],
    combos: [['chest_pain', 'breathlessness']],
    source: 'nice_chest_pain',
  },
  {
    id: 'stroke',
    level: 'emergency',
    en: 'Sudden face drooping, arm weakness, or difficulty speaking',
    ar: 'تدلٍ مفاجئ في الوجه أو ضعف في الذراع أو صعوبة في الكلام',
    concepts: [['face','arm','leg','speech','speak','word','vision','وجه','ذراع','يد','رجل','كلام','نطق','رؤية'],['weak','droop','numb','sudden','slur','paralys','blurred','ضعف','تنميل','مفاجئ','شلل','مائل']],
    match: ['face drooping', 'slurred speech', "can't speak", 'cannot speak', 'weakness on one side', 'one side of my body', 'numb on one side', 'ضعف في جهة واحدة', 'صعوبة في الكلام', 'تنميل نصف الجسم', 'فمي مائل'],
    source: 'cdc_stroke',
  },
  {
    id: 'sepsis',
    level: 'emergency',
    en: 'Fever with confusion, very fast breathing, cold or mottled skin',
    ar: 'حمى مع تشوش أو تنفس سريع جدًا أو برودة وتبقع في الجلد',
    concepts: [['fever','temperature','hot','burning up','feverish','حمى','حرارة','سخونة'],['confus','drowsy','unrespons','shiver','rigor','breathing fast','mottl','تشوش','خمول','رعشة','لا يستجيب','تنفس سريع']],
    match: ['confused and feverish', 'fever and confusion', 'mottled skin', 'cannot stay awake', 'حمى مع تشوش', 'لا يستيقظ', 'جلد متبقع'],
    source: 'nice_sepsis',
  },
  {
    id: 'thunderclap_headache',
    level: 'emergency',
    en: 'Headache that reached maximum intensity within seconds, or headache with neck stiffness and fever',
    ar: 'صداع يصل لأقصى شدة خلال ثوانٍ، أو صداع مع تيبس الرقبة وحمى',
    concepts: [['headache','head','صداع','رأس'],['sudden','worst','seconds','explod','neck stiff','vomit','مفاجئ','أسوأ','ثوان','تيبس','انفجار']],
    match: ['worst headache of my life', 'sudden severe headache', 'thunderclap', 'neck stiffness', 'stiff neck and fever', 'أسوأ صداع في حياتي', 'صداع مفاجئ شديد', 'تيبس الرقبة'],
    source: 'nice_headache',
  },
  {
    id: 'anaphylaxis',
    level: 'emergency',
    en: 'Swelling of the lips, tongue or throat, or difficulty breathing after exposure to something',
    ar: 'تورم في الشفاه أو اللسان أو الحلق، أو صعوبة تنفس بعد التعرض لشيء',
    concepts: [['throat','tongue','lip','face','حلق','لسان','شفاه','وجه'],['swell','closing','tight','breath','wheez','تورم','انتفاخ','ضيق','اختناق']],
    match: ['throat closing', 'throat is closing', 'tongue swelling', 'tongue is swelling', 'lips swelling', 'lips are swelling', 'swollen tongue', 'trouble swallowing and breathing', 'تورم اللسان', 'تورم الحلق', 'انتفاخ الشفايف', 'لساني متورم'],
    source: 'nhs_conditions',
  },
  {
    id: 'cauda_equina',
    level: 'emergency',
    en: 'Back pain with loss of bladder or bowel control, or numbness around the groin',
    ar: 'ألم ظهر مع فقدان التحكم في البول أو البراز، أو تنميل حول المنطقة الحساسة',
    concepts: [['back','spine','ظهر','عمود'],['bladder','bowel','urine','groin','saddle','numb','incontin','wetting','wet myself','cannot hold','مثانة','بول','براز','تنميل','سلس']],
    match: ['cannot control my bladder', 'lost bowel control', 'numbness in my groin', 'saddle numbness', 'لا أتحكم في البول', 'تنميل بين الفخذين'],
    source: 'nice_low_back',
  },
  {
    id: 'bleeding',
    level: 'emergency',
    en: 'Heavy or uncontrolled bleeding, vomiting blood, or black tarry stool',
    ar: 'نزيف شديد أو تقيؤ دم أو براز أسود قطراني',
    concepts: [['blood','bleed','stool','vomit','دم','نزيف','براز','قيء'],['heavy','black','tarry','coffee','cannot stop','شديد','أسود','قطراني','لا يتوقف']],
    match: ['vomiting blood', 'blood in my vomit', 'black stool', 'heavy bleeding', 'تقيؤ دم', 'براز أسود', 'نزيف شديد'],
    source: 'nhs_conditions',
  },
  {
    id: 'pulmonary_embolism',
    level: 'emergency',
    en: 'Sudden breathlessness with calf pain or swelling, or chest pain that is worse on breathing in',
    ar: 'ضيق نفس مفاجئ مع ألم أو تورم في الساق، أو ألم صدر يزداد مع الشهيق',
    concepts: [['breath', 'breathless', 'short of breath', 'نفس', 'تنفس'], ['calf', 'leg swelling', 'swollen leg', 'ساق', 'تورم']],
    match: ['sudden shortness of breath and leg swelling', 'ضيق نفس مفاجئ مع تورم الساق'],
    source: 'nhs_conditions',
  },
  {
    id: 'severe_asthma',
    level: 'emergency',
    en: 'Too breathless to finish a sentence, or an inhaler that is no longer helping',
    ar: 'ضيق نفس يمنع إكمال الجملة، أو بخاخ لم يعد ينفع',
    concepts: [['inhaler', 'asthma', 'wheez', 'بخاخ', 'ربو', 'أزيز'], ['not working', 'no longer help', 'cannot finish', 'cannot speak', 'worse', 'لا ينفع', 'لا أستطيع الكلام', 'يزداد']],
    match: ['cannot finish a sentence', 'inhaler is not working', 'بخاخي ما بينفع'],
    source: 'nhs_conditions',
  },
  {
    id: 'acute_vision_loss',
    level: 'emergency',
    en: 'Sudden loss of vision, or a curtain across the sight in one eye',
    ar: 'فقدان مفاجئ للرؤية أو ستارة على الرؤية في عين واحدة',
    concepts: [['vision', 'sight', 'see', 'eye', 'رؤية', 'بصر', 'عين'], ['lost', 'loss', 'sudden', 'curtain', 'black', 'blurred suddenly', 'فقدت', 'مفاجئ', 'ستارة']],
    match: ['sudden loss of vision', 'curtain over my eye', 'فقدت الرؤية فجأة'],
    source: 'nhs_conditions',
  },
  {
    id: 'diabetic_emergency',
    level: 'emergency',
    en: 'Very high thirst with vomiting, deep breathing or drowsiness in someone with diabetes',
    ar: 'عطش شديد مع قيء أو تنفس عميق أو خمول لدى مريض سكري',
    concepts: [['diabet', 'sugar', 'insulin', 'سكري', 'إنسولين'], ['vomit', 'drowsy', 'confus', 'deep breathing', 'cannot keep', 'قيء', 'خمول', 'تشوش']],
    match: ['diabetic and vomiting and drowsy', 'سكري مع قيء وخمول'],
    source: 'nice_sepsis',
  },
  {
    id: 'testicular_or_ectopic_pain',
    level: 'emergency',
    en: 'Sudden severe pain in the lower abdomen or groin',
    ar: 'ألم شديد مفاجئ أسفل البطن أو في المنطقة الأربية',
    concepts: [['groin', 'testic', 'lower abdomen', 'pelvic', 'أربية', 'خصية', 'أسفل البطن'], ['sudden severe', 'agonis', 'excruciat', 'severe pain', 'ألم شديد', 'مفاجئ']],
    match: ['sudden severe groin pain', 'ألم شديد مفاجئ في الخصية'],
    source: 'nhs_conditions',
  },
  {
    id: 'self_harm',
    level: 'support',
    en: 'Thoughts of harming yourself',
    ar: 'أفكار بإيذاء النفس',
    // Unambiguous wording fires on its own.
    match: ['kill myself', 'killing myself', 'end my life', 'ending my life', 'ending it all',
      'take my own life', 'suicide', 'suicidal', 'self harm', 'self-harm',
      'أنهي حياتي', 'إنهاء حياتي', 'إيذاء نفسي', 'الانتحار', 'انتحار'],
    // "I hurt myself" is usually an injury, so it only counts alongside intent.
    concepts: [['hurt myself', 'harm myself', 'أؤذي نفسي'],
      ['want', 'thinking', 'think about', 'plan', 'feel like', 'going to', 'cannot go on', "can't go on",
        'أريد', 'أفكر', 'ما عاد أقدر', 'أخطط']],
    source: 'who_ai_health',
  },
  {
    id: 'pregnancy_abdo',
    level: 'urgent',
    en: 'Abdominal pain or bleeding during pregnancy',
    ar: 'ألم في البطن أو نزيف أثناء الحمل',
    match: ['pregnant and bleeding', 'pregnant with pain', 'حامل ونزيف', 'حامل مع ألم'],
    source: 'nhs_conditions',
  },
  {
    id: 'infant',
    level: 'urgent',
    en: 'A baby under three months with a fever',
    ar: 'رضيع أقل من ثلاثة أشهر لديه حمى',
    match: ['my baby has a fever', 'newborn fever', 'رضيع عنده حرارة', 'مولود حمى'],
    source: 'nice_sepsis',
  },
];

// ---------------------------------------------------------------------------
// Candidate explanations
// ---------------------------------------------------------------------------
const CONDITIONS = [
  {
    id: 'acs',
    en: 'A heart-related cause of chest pain',
    ar: 'سبب قلبي لألم الصدر',
    specialty: 'Cardiology',
    urgency: 'emergency',
    supports: { chest_pain: 3, breathlessness: 2, nausea: 1, dizziness: 1, fatigue: 1 },
    plain_en: 'Chest discomfort can come from the heart muscle not getting enough blood flow. This is time-critical, so it is assessed before gentler explanations.',
    plain_ar: 'قد ينشأ انزعاج الصدر من نقص تدفق الدم لعضلة القلب. هذا الاحتمال حساس للوقت، لذلك يُقيَّم قبل الاحتمالات الأبسط.',
    discriminators_en: ['Whether the pain comes on with exertion and eases with rest', 'Whether it spreads to the arm, jaw or back', 'Whether it is reproduced by pressing on the chest wall'],
    discriminators_ar: ['هل يظهر الألم مع المجهود ويخف بالراحة', 'هل ينتشر إلى الذراع أو الفك أو الظهر', 'هل يتكرر الألم عند الضغط على جدار الصدر'],
    investigations_en: ['ECG', 'Blood tests for cardiac markers', 'Clinical examination and history'],
    investigations_ar: ['تخطيط القلب', 'تحاليل دم لمؤشرات القلب', 'الفحص السريري والتاريخ المرضي'],
    sources: ['nice_chest_pain'],
  },
  {
    id: 'musculoskeletal_chest',
    en: 'A chest wall or muscular cause',
    ar: 'سبب عضلي أو في جدار الصدر',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { chest_pain: 2, joint_pain: 1 },
    opposes: { breathlessness: 1, nausea: 1 },
    plain_en: 'Muscles, ribs and the joints between them can produce sharp, localised chest pain that changes with movement or position.',
    plain_ar: 'يمكن للعضلات والأضلاع والمفاصل بينها أن تسبب ألمًا حادًا موضعيًا في الصدر يتغير مع الحركة أو الوضعية.',
    discriminators_en: ['Whether pressing on the painful spot reproduces the pain', 'Whether the pain changes with position or deep breathing', 'Recent lifting, coughing or injury'],
    discriminators_ar: ['هل يتكرر الألم عند الضغط على المنطقة المؤلمة', 'هل يتغير الألم مع الوضعية أو التنفس العميق', 'حمل أوزان أو سعال أو إصابة حديثة'],
    investigations_en: ['Clinical examination', 'Usually no imaging is needed unless features change'],
    investigations_ar: ['الفحص السريري', 'عادة لا حاجة لتصوير إلا إذا تغيرت الأعراض'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'reflux',
    en: 'Acid reflux or another digestive cause',
    ar: 'ارتجاع حمضي أو سبب هضمي آخر',
    specialty: 'Gastroenterology',
    urgency: 'routine',
    supports: { chest_pain: 2, nausea: 1, abdominal_pain: 2 },
    plain_en: 'Stomach acid moving into the food pipe can cause a burning discomfort behind the breastbone, often after meals or when lying flat.',
    plain_ar: 'قد يسبب ارتداد حمض المعدة إلى المريء حرقة خلف عظمة الصدر، غالبًا بعد الأكل أو عند الاستلقاء.',
    discriminators_en: ['Relationship to meals and lying flat', 'Burning quality rather than pressure', 'Response to antacids'],
    discriminators_ar: ['علاقته بالوجبات والاستلقاء', 'طابع الحرقة بدل الضغط', 'الاستجابة لمضادات الحموضة'],
    investigations_en: ['Clinical history', 'Trial of treatment decided by a clinician', 'Endoscopy only if warning features are present'],
    investigations_ar: ['التاريخ السريري', 'تجربة علاجية يقررها الطبيب', 'منظار فقط عند وجود علامات تحذيرية'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'anxiety_panic',
    en: 'Anxiety or a panic response',
    ar: 'قلق أو نوبة هلع',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { chest_pain: 1, breathlessness: 2, palpitations: 2, dizziness: 1, anxiety: 3 },
    plain_en: 'A strong stress response can produce a racing heart, tight chest and breathlessness. It is considered after time-critical causes have been addressed.',
    plain_ar: 'قد تسبب استجابة التوتر القوية تسارع القلب وضيق الصدر وضيق النفس. يُنظر فيها بعد استبعاد الأسباب الحساسة للوقت.',
    discriminators_en: ['Whether episodes are linked to specific triggers', 'How quickly symptoms peak and settle', 'Tingling in the hands or around the mouth'],
    discriminators_ar: ['هل ترتبط النوبات بمحفزات معينة', 'سرعة بلوغ الأعراض ذروتها وزوالها', 'تنميل في اليدين أو حول الفم'],
    investigations_en: ['Clinical assessment', 'Basic tests to exclude other causes if indicated'],
    investigations_ar: ['تقييم سريري', 'فحوصات أساسية لاستبعاد أسباب أخرى عند الحاجة'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'lower_resp_infection',
    en: 'A chest infection',
    ar: 'التهاب في الصدر',
    specialty: 'General Practice',
    urgency: 'urgent',
    supports: { cough: 3, fever: 2, breathlessness: 2, fatigue: 1, chest_pain: 1 },
    plain_en: 'An infection in the airways or lungs typically brings cough, fever and breathlessness together over days.',
    plain_ar: 'يسبب التهاب المجاري التنفسية أو الرئتين عادة سعالًا وحمى وضيق نفس تتطور خلال أيام.',
    discriminators_en: ['Colour and volume of sputum', 'Breathing rate and oxygen level', 'Findings when the chest is listened to'],
    discriminators_ar: ['لون وكمية البلغم', 'معدل التنفس ومستوى الأكسجين', 'ما يُسمع عند فحص الصدر'],
    investigations_en: ['Clinical examination', 'Oxygen saturation', 'Chest X-ray when indicated'],
    investigations_ar: ['الفحص السريري', 'قياس تشبع الأكسجين', 'أشعة صدر عند الحاجة'],
    sources: ['nice_sepsis', 'nhs_conditions'],
  },
  {
    id: 'viral_uri',
    en: 'A common viral infection of the upper airway',
    ar: 'عدوى فيروسية في المجرى التنفسي العلوي',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { sore_throat: 3, cough: 2, fever: 1, fatigue: 1, headache: 1 },
    opposes: { breathlessness: 1 },
    plain_en: 'Most sore throats and coughs come from self-limiting viral infections that settle over about a week.',
    plain_ar: 'معظم حالات التهاب الحلق والسعال تنتج عن عدوى فيروسية محدودة ذاتيًا تزول خلال أسبوع تقريبًا.',
    discriminators_en: ['Presence of tonsillar exudate and swollen neck glands', 'Absence of cough with fever', 'How long symptoms have lasted'],
    discriminators_ar: ['وجود إفرازات على اللوزتين وتضخم غدد الرقبة', 'غياب السعال مع وجود حمى', 'مدة استمرار الأعراض'],
    investigations_en: ['Clinical examination', 'Throat swab only in selected cases'],
    investigations_ar: ['الفحص السريري', 'مسحة حلق في حالات مختارة فقط'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'migraine',
    en: 'Migraine',
    ar: 'شقيقة (ميغرين)',
    specialty: 'Neurology',
    urgency: 'routine',
    supports: { headache: 3, nausea: 2, dizziness: 1 },
    plain_en: 'Migraine usually builds over minutes to hours, often on one side, and is commonly worsened by light, sound and movement.',
    plain_ar: 'تتطور الشقيقة عادة خلال دقائق إلى ساعات، غالبًا في جهة واحدة، وتزداد مع الضوء والصوت والحركة.',
    discriminators_en: ['Whether light and sound make it worse', 'Whether there is visual aura beforehand', 'Pattern of previous similar attacks'],
    discriminators_ar: ['هل يزداد الألم مع الضوء والصوت', 'هل تسبقه هالة بصرية', 'نمط النوبات المشابهة السابقة'],
    investigations_en: ['Clinical history', 'Imaging only if warning features are present'],
    investigations_ar: ['التاريخ السريري', 'تصوير فقط عند وجود علامات تحذيرية'],
    sources: ['nice_headache'],
  },
  {
    id: 'tension_headache',
    en: 'Tension-type headache',
    ar: 'صداع توتري',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { headache: 2, fatigue: 1, anxiety: 1 },
    opposes: { nausea: 1 },
    plain_en: 'A band-like pressure across the head, usually on both sides, without nausea or sensitivity to light.',
    plain_ar: 'ضغط يشبه الشريط حول الرأس، غالبًا في الجهتين، دون غثيان أو حساسية للضوء.',
    discriminators_en: ['Both sides versus one side', 'Absence of nausea', 'Relationship to stress, screens or posture'],
    discriminators_ar: ['الجهتان مقابل جهة واحدة', 'غياب الغثيان', 'علاقته بالتوتر أو الشاشات أو وضعية الجلوس'],
    investigations_en: ['Clinical history and examination'],
    investigations_ar: ['التاريخ السريري والفحص'],
    sources: ['nice_headache'],
  },
  {
    id: 'dehydration',
    en: 'Dehydration or low blood pressure on standing',
    ar: 'جفاف أو انخفاض ضغط عند الوقوف',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { dizziness: 3, fatigue: 2, headache: 1, nausea: 1, diarrhoea: 1 },
    plain_en: 'Losing fluid, or standing up quickly, can briefly reduce blood flow to the brain and cause light-headedness.',
    plain_ar: 'قد يؤدي فقدان السوائل أو الوقوف السريع إلى نقص مؤقت في تدفق الدم للدماغ ويسبب دوخة.',
    discriminators_en: ['Whether symptoms happen on standing up', 'Fluid intake and recent fluid losses', 'Blood pressure lying and standing'],
    discriminators_ar: ['هل تظهر الأعراض عند الوقوف', 'كمية السوائل والفقد الأخير', 'ضغط الدم أثناء الاستلقاء والوقوف'],
    investigations_en: ['Blood pressure measurement', 'Basic blood tests when indicated'],
    investigations_ar: ['قياس ضغط الدم', 'تحاليل دم أساسية عند الحاجة'],
    sources: ['medlineplus'],
  },
  {
    id: 'gastroenteritis',
    en: 'A short-lived gut infection',
    ar: 'التهاب معوي قصير المدى',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { diarrhoea: 3, nausea: 2, abdominal_pain: 2, fever: 1 },
    plain_en: 'Sudden diarrhoea and vomiting, often with cramping, that settles within a few days in most people.',
    plain_ar: 'إسهال وقيء مفاجئان مع تقلصات غالبًا، ويتحسنان خلال أيام قليلة لدى معظم الناس.',
    discriminators_en: ['Blood in the stool', 'Signs of dehydration', 'Recent travel or shared illness'],
    discriminators_ar: ['وجود دم في البراز', 'علامات الجفاف', 'سفر حديث أو مرض مشترك'],
    investigations_en: ['Clinical assessment', 'Stool testing in selected cases'],
    investigations_ar: ['التقييم السريري', 'تحليل براز في حالات مختارة'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'appendicitis',
    en: 'An inflamed appendix or another surgical abdominal cause',
    ar: 'التهاب الزائدة أو سبب جراحي آخر في البطن',
    specialty: 'General Surgery',
    urgency: 'emergency',
    supports: { abdominal_pain: 3, nausea: 2, fever: 2 },
    opposes: { diarrhoea: 1 },
    plain_en: 'Pain that starts centrally and moves to the lower right abdomen, becoming constant and worse with movement, needs prompt surgical assessment.',
    plain_ar: 'ألم يبدأ في وسط البطن وينتقل إلى أسفل اليمين ويصبح مستمرًا ويزداد مع الحركة، يحتاج تقييمًا جراحيًا عاجلًا.',
    discriminators_en: ['Whether the pain has moved location', 'Tenderness in the lower right abdomen', 'Pain on movement or coughing'],
    discriminators_ar: ['هل انتقل مكان الألم', 'ألم عند الضغط أسفل يمين البطن', 'ازدياد الألم مع الحركة أو السعال'],
    investigations_en: ['Surgical examination', 'Blood tests', 'Ultrasound or CT as decided clinically'],
    investigations_ar: ['فحص جراحي', 'تحاليل دم', 'موجات صوتية أو أشعة مقطعية حسب القرار السريري'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'uti',
    en: 'A urinary tract infection',
    ar: 'التهاب في المسالك البولية',
    specialty: 'General Practice',
    urgency: 'urgent',
    supports: { urinary: 3, abdominal_pain: 1, fever: 1, back_pain: 1 },
    plain_en: 'Burning on passing urine and needing to go more often are the usual features; fever and back pain suggest the kidneys are involved.',
    plain_ar: 'الحرقان أثناء التبول وزيادة عدد المرات هما العلامتان المعتادتان؛ ووجود حمى وألم ظهر يشير إلى تأثر الكلى.',
    discriminators_en: ['Fever and flank pain', 'Blood in the urine', 'Pregnancy or catheter use'],
    discriminators_ar: ['حمى وألم في الخاصرة', 'دم في البول', 'الحمل أو استخدام قسطرة'],
    investigations_en: ['Urine dipstick and culture', 'Clinical assessment'],
    investigations_ar: ['تحليل وزراعة بول', 'التقييم السريري'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'mechanical_back',
    en: 'Mechanical low back pain',
    ar: 'ألم أسفل الظهر الميكانيكي',
    specialty: 'Orthopaedics',
    urgency: 'routine',
    supports: { back_pain: 3, joint_pain: 1 },
    plain_en: 'Most back pain comes from muscles, discs and joints, improves with gentle movement, and does not need imaging.',
    plain_ar: 'معظم آلام الظهر تنشأ من العضلات والأقراص والمفاصل، وتتحسن بالحركة اللطيفة، ولا تحتاج تصويرًا.',
    discriminators_en: ['Whether pain travels below the knee', 'Night pain or weight loss', 'Bladder or bowel changes'],
    discriminators_ar: ['هل ينتشر الألم أسفل الركبة', 'ألم ليلي أو فقدان وزن', 'تغيرات في البول أو البراز'],
    investigations_en: ['Clinical examination', 'Imaging only if warning features are present'],
    investigations_ar: ['الفحص السريري', 'تصوير فقط عند وجود علامات تحذيرية'],
    sources: ['nice_low_back'],
  },
  {
    id: 'allergic_reaction',
    en: 'An allergic skin reaction',
    ar: 'تفاعل جلدي تحسسي',
    specialty: 'Dermatology',
    urgency: 'urgent',
    supports: { rash: 3, fatigue: 0.5 },
    plain_en: 'Raised, itchy patches appearing within hours of a food, medicine or contact exposure often point to an allergic reaction.',
    plain_ar: 'ظهور بقع مرتفعة وحاكة خلال ساعات من تناول طعام أو دواء أو تلامس يشير غالبًا إلى تفاعل تحسسي.',
    discriminators_en: ['Timing relative to a new medicine or food', 'Whether the rash blanches when pressed', 'Any lip, tongue or throat swelling'],
    discriminators_ar: ['التوقيت بالنسبة لدواء أو طعام جديد', 'هل يبهت الطفح عند الضغط عليه', 'أي تورم في الشفاه أو اللسان أو الحلق'],
    investigations_en: ['Clinical examination', 'Allergy assessment when the trigger is unclear'],
    investigations_ar: ['الفحص السريري', 'تقييم الحساسية عند عدم وضوح المحفز'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'anaemia_fatigue',
    en: 'Anaemia or another cause of persistent tiredness',
    ar: 'فقر دم أو سبب آخر للتعب المستمر',
    specialty: 'Internal Medicine',
    urgency: 'routine',
    supports: { fatigue: 3, dizziness: 1, breathlessness: 1, palpitations: 1 },
    plain_en: 'Tiredness lasting weeks, especially with breathlessness on exertion, is commonly investigated with simple blood tests.',
    plain_ar: 'التعب المستمر لأسابيع، خاصة مع ضيق نفس عند المجهود، يُفحص عادة بتحاليل دم بسيطة.',
    discriminators_en: ['Duration of tiredness', 'Heavy periods or known blood loss', 'Diet and absorption'],
    discriminators_ar: ['مدة التعب', 'دورة غزيرة أو فقد دم معروف', 'النظام الغذائي والامتصاص'],
    investigations_en: ['Full blood count', 'Iron studies, thyroid tests as decided clinically'],
    investigations_ar: ['صورة دم كاملة', 'تحاليل الحديد والغدة الدرقية حسب القرار السريري'],
    sources: ['medlineplus'],
  },

  {
    id: 'asthma_flare',
    en: 'An asthma flare or reactive airways',
    ar: 'نوبة ربو أو تهيج في المجاري الهوائية',
    specialty: 'General Practice',
    urgency: 'urgent',
    supports: { wheeze: 3, breathlessness: 2, cough: 2, chest_pain: 1 },
    plain_en: 'Narrowed airways produce wheeze, cough and tightness that often worsen at night, with exercise, or around a known trigger.',
    plain_ar: 'يسبب ضيق المجاري الهوائية أزيزًا وسعالًا وضيقًا يزداد غالبًا ليلًا أو مع المجهود أو قرب محفز معروف.',
    discriminators_en: ['Whether an inhaler relieves it', 'Night-time and early-morning pattern', 'A known trigger such as dust, cold air or exercise'],
    discriminators_ar: ['هل يخف بالبخاخ', 'نمط الليل والصباح الباكر', 'محفز معروف مثل الغبار أو الهواء البارد أو المجهود'],
    investigations_en: ['Peak flow measurement', 'Oxygen saturation', 'Spirometry when stable'],
    investigations_ar: ['قياس ذروة الجريان', 'تشبع الأكسجين', 'قياس التنفس عند الاستقرار'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'venous_thrombosis',
    en: 'A clot in a leg vein, or a clot that has travelled to the lung',
    ar: 'جلطة في وريد الساق أو جلطة انتقلت إلى الرئة',
    specialty: 'Internal Medicine',
    urgency: 'emergency',
    supports: { leg_swelling: 3, breathlessness: 2, chest_pain: 1 },
    plain_en: 'Swelling and pain in one calf, especially after immobility, surgery or a long flight, is assessed urgently because a clot can travel to the lung.',
    plain_ar: 'تورم وألم في ساق واحدة، خاصة بعد قلة الحركة أو جراحة أو رحلة طويلة، يُقيَّم بشكل عاجل لأن الجلطة قد تنتقل للرئة.',
    discriminators_en: ['One leg versus both', 'Recent immobility, surgery or long travel', 'Breathlessness or pain on breathing in'],
    discriminators_ar: ['ساق واحدة أم الاثنتان', 'قلة حركة أو جراحة أو سفر طويل حديثًا', 'ضيق نفس أو ألم مع الشهيق'],
    investigations_en: ['Clinical scoring by a clinician', 'D-dimer', 'Ultrasound or CT as decided clinically'],
    investigations_ar: ['تقييم سريري بمقياس مخصص', 'تحليل D-dimer', 'موجات صوتية أو أشعة مقطعية حسب القرار السريري'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'renal_colic',
    en: 'A stone in the urinary tract',
    ar: 'حصوة في المسالك البولية',
    specialty: 'Urology',
    urgency: 'urgent',
    supports: { back_pain: 2, abdominal_pain: 2, nausea: 1, urinary: 2 },
    plain_en: 'Severe pain coming in waves from the flank towards the groin, often with nausea and blood in the urine.',
    plain_ar: 'ألم شديد على شكل موجات من الخاصرة نحو المنطقة الأربية، غالبًا مع غثيان ودم في البول.',
    discriminators_en: ['Waves of pain rather than constant pain', 'Blood in the urine', 'Inability to find a comfortable position'],
    discriminators_ar: ['ألم على موجات بدل الألم المستمر', 'دم في البول', 'عدم القدرة على إيجاد وضعية مريحة'],
    investigations_en: ['Urine dipstick', 'CT of the urinary tract when indicated'],
    investigations_ar: ['تحليل بول', 'أشعة مقطعية للمسالك عند الحاجة'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'biliary_colic',
    en: 'Gallstones or another cause of upper abdominal pain',
    ar: 'حصوات المرارة أو سبب آخر لألم أعلى البطن',
    specialty: 'General Surgery',
    urgency: 'urgent',
    supports: { abdominal_pain: 3, nausea: 2, fever: 1 },
    plain_en: 'Pain under the right ribs after fatty food, lasting from minutes to hours, sometimes spreading to the right shoulder blade.',
    plain_ar: 'ألم تحت الأضلاع اليمنى بعد الطعام الدسم، يستمر من دقائق إلى ساعات، وقد ينتشر إلى لوح الكتف الأيمن.',
    discriminators_en: ['Relation to fatty meals', 'Fever and yellowing of the eyes', 'Tenderness under the right ribs'],
    discriminators_ar: ['علاقته بالوجبات الدسمة', 'الحمى واصفرار العينين', 'ألم عند الضغط تحت الأضلاع اليمنى'],
    investigations_en: ['Abdominal ultrasound', 'Liver blood tests'],
    investigations_ar: ['موجات صوتية للبطن', 'تحاليل وظائف الكبد'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'peptic_ulcer',
    en: 'Gastritis or a stomach ulcer',
    ar: 'التهاب المعدة أو قرحة',
    specialty: 'Gastroenterology',
    urgency: 'routine',
    supports: { abdominal_pain: 2, nausea: 2, chest_pain: 1 },
    plain_en: 'Burning pain in the upper abdomen that changes with eating, sometimes worse at night.',
    plain_ar: 'ألم حارق أعلى البطن يتغير مع الأكل، وقد يزداد ليلًا.',
    discriminators_en: ['Whether food relieves or worsens it', 'Use of anti-inflammatory painkillers', 'Black stool or vomiting blood, which changes urgency immediately'],
    discriminators_ar: ['هل يخف الألم بالأكل أم يزداد', 'استخدام مسكنات مضادة للالتهاب', 'براز أسود أو تقيؤ دم، وهو ما يغير الإلحاح فورًا'],
    investigations_en: ['Clinical history', 'Testing for H. pylori', 'Endoscopy if warning features are present'],
    investigations_ar: ['التاريخ السريري', 'فحص جرثومة المعدة', 'منظار عند وجود علامات تحذيرية'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'sinusitis',
    en: 'Sinus inflammation',
    ar: 'التهاب الجيوب الأنفية',
    specialty: 'General Practice',
    urgency: 'routine',
    supports: { facial_pain: 3, headache: 1, cough: 1, fever: 1 },
    plain_en: 'Pressure across the cheeks or forehead with a blocked nose, usually after a cold, worse when bending forward.',
    plain_ar: 'ضغط في الخدين أو الجبهة مع انسداد الأنف، غالبًا بعد نزلة برد، ويزداد عند الانحناء للأمام.',
    discriminators_en: ['Whether it worsens on bending forward', 'How long the blocked nose has lasted', 'One-sided facial swelling or eye involvement'],
    discriminators_ar: ['هل يزداد عند الانحناء للأمام', 'مدة انسداد الأنف', 'تورم في جهة واحدة من الوجه أو تأثر العين'],
    investigations_en: ['Clinical examination', 'Imaging only for complications'],
    investigations_ar: ['الفحص السريري', 'تصوير فقط عند المضاعفات'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'otitis',
    en: 'An ear infection',
    ar: 'التهاب في الأذن',
    specialty: 'ENT',
    urgency: 'urgent',
    supports: { ear_pain: 3, fever: 1, sore_throat: 1 },
    plain_en: 'Ear pain with reduced hearing, often after a cold, sometimes with discharge.',
    plain_ar: 'ألم في الأذن مع ضعف السمع، غالبًا بعد نزلة برد، وأحيانًا مع إفرازات.',
    discriminators_en: ['Discharge from the ear', 'Swelling or redness behind the ear', 'Hearing loss on one side'],
    discriminators_ar: ['إفرازات من الأذن', 'تورم أو احمرار خلف الأذن', 'ضعف سمع في جهة واحدة'],
    investigations_en: ['Examination of the ear drum'],
    investigations_ar: ['فحص طبلة الأذن'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'conjunctivitis',
    en: 'Conjunctivitis or another surface eye problem',
    ar: 'التهاب الملتحمة أو مشكلة سطحية في العين',
    specialty: 'Ophthalmology',
    urgency: 'urgent',
    supports: { eye_redness: 3, rash: 0.5 },
    plain_en: 'A red, gritty eye with discharge and normal vision is usually a surface problem rather than something inside the eye.',
    plain_ar: 'العين الحمراء مع إحساس بالرمل وإفرازات ورؤية طبيعية تكون عادة مشكلة سطحية لا داخل العين.',
    discriminators_en: ['Whether vision is affected', 'Pain inside the eye versus surface irritation', 'Sensitivity to light'],
    discriminators_ar: ['هل تأثرت الرؤية', 'ألم داخل العين مقابل تهيج سطحي', 'الحساسية للضوء'],
    investigations_en: ['Eye examination including vision testing'],
    investigations_ar: ['فحص العين مع قياس الإبصار'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'bppv_vertigo',
    en: 'Inner-ear vertigo',
    ar: 'دوار من الأذن الداخلية',
    specialty: 'ENT',
    urgency: 'routine',
    supports: { vertigo_spin: 3, dizziness: 2, nausea: 1 },
    plain_en: 'Short spinning episodes triggered by turning the head or rolling over in bed, with normal hearing and no weakness.',
    plain_ar: 'نوبات دوران قصيرة تحدث عند تحريك الرأس أو التقلب في السرير، مع سمع طبيعي ودون ضعف.',
    discriminators_en: ['Whether head position triggers it', 'How long each episode lasts', 'Any weakness, double vision or difficulty speaking, which changes the assessment entirely'],
    discriminators_ar: ['هل تثيره وضعية الرأس', 'مدة كل نوبة', 'أي ضعف أو ازدواج رؤية أو صعوبة كلام، وهو ما يغير التقييم تمامًا'],
    investigations_en: ['Positional testing by a clinician', 'Neurological examination'],
    investigations_ar: ['اختبار وضعي يجريه الطبيب', 'فحص عصبي'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'cellulitis',
    en: 'A spreading skin infection',
    ar: 'التهاب جلدي منتشر',
    specialty: 'General Practice',
    urgency: 'urgent',
    supports: { skin_infection: 3, fever: 2, rash: 1, leg_swelling: 1 },
    plain_en: 'Skin that is hot, red, tender and spreading, often on the lower leg, commonly with fever.',
    plain_ar: 'جلد ساخن ومحمر ومؤلم وينتشر، غالبًا في الساق، ومع حمى عادة.',
    discriminators_en: ['Whether the edge is spreading over hours', 'Fever and feeling unwell', 'A break in the skin as an entry point'],
    discriminators_ar: ['هل تتسع الحافة خلال ساعات', 'حمى وشعور بالتوعك', 'وجود جرح كنقطة دخول'],
    investigations_en: ['Clinical examination', 'Blood tests if unwell'],
    investigations_ar: ['الفحص السريري', 'تحاليل دم عند التوعك'],
    sources: ['nhs_conditions'],
  },
  {
    id: 'hyperglycaemia',
    en: 'High blood sugar, diagnosed or undiagnosed',
    ar: 'ارتفاع سكر الدم، مشخّص أو غير مشخّص',
    specialty: 'Endocrinology',
    urgency: 'urgent',
    supports: { thirst: 3, fatigue: 2, weight_loss: 2, urinary: 1 },
    plain_en: 'Thirst, passing urine often, tiredness and weight loss together are the pattern that prompts a blood sugar test.',
    plain_ar: 'العطش وكثرة التبول والتعب وفقدان الوزن معًا هو النمط الذي يستدعي فحص سكر الدم.',
    discriminators_en: ['How long the thirst has lasted', 'Weight change without trying', 'Vomiting or drowsiness, which makes it an emergency'],
    discriminators_ar: ['مدة العطش', 'تغير الوزن دون قصد', 'القيء أو الخمول، وهو ما يجعلها حالة طارئة'],
    investigations_en: ['Blood glucose', 'HbA1c', 'Urine ketones when unwell'],
    investigations_ar: ['سكر الدم', 'السكر التراكمي', 'كيتونات البول عند التوعك'],
    sources: ['medlineplus'],
  },
  {
    id: 'thyroid',
    en: 'An underactive or overactive thyroid',
    ar: 'خمول أو فرط في الغدة الدرقية',
    specialty: 'Endocrinology',
    urgency: 'routine',
    supports: { fatigue: 2, weight_loss: 2, palpitations: 2, night_sweats: 1 },
    plain_en: 'Thyroid problems can show up as tiredness, weight change, palpitations or heat intolerance, and are checked with a simple blood test.',
    plain_ar: 'قد تظهر مشاكل الغدة الدرقية كتعب أو تغير وزن أو خفقان أو عدم تحمل الحرارة، وتُفحص بتحليل دم بسيط.',
    discriminators_en: ['Direction of weight change', 'Heat or cold intolerance', 'Neck swelling'],
    discriminators_ar: ['اتجاه تغير الوزن', 'عدم تحمل الحر أو البرد', 'تورم في الرقبة'],
    investigations_en: ['Thyroid function blood tests'],
    investigations_ar: ['تحاليل وظائف الغدة الدرقية'],
    sources: ['medlineplus'],
  },
  {
    id: 'febrile_illness',
    en: 'A systemic febrile illness, including mosquito-borne infection where relevant',
    ar: 'مرض حموي جهازي، بما في ذلك العدوى المنقولة بالبعوض عند الاقتضاء',
    specialty: 'Internal Medicine',
    urgency: 'urgent',
    supports: { fever: 3, headache: 2, fatigue: 2, joint_pain: 2, night_sweats: 1 },
    plain_en: 'Fever with headache, aching joints and exhaustion, particularly after travel or in an area where malaria or dengue circulate, is assessed promptly.',
    plain_ar: 'الحمى مع الصداع وآلام المفاصل والإرهاق، خاصة بعد السفر أو في منطقة تنتشر فيها الملاريا أو حمى الضنك، تُقيَّم سريعًا.',
    discriminators_en: ['Travel history and mosquito exposure', 'Pattern of the fever', 'Rash, bleeding or confusion'],
    discriminators_ar: ['تاريخ السفر والتعرض للبعوض', 'نمط الحمى', 'طفح أو نزيف أو تشوش'],
    investigations_en: ['Malaria testing where relevant', 'Full blood count', 'Clinical assessment'],
    investigations_ar: ['فحص الملاريا عند الاقتضاء', 'صورة دم كاملة', 'تقييم سريري'],
    sources: ['who_ai_health', 'nhs_conditions'],
  },
];

// ---------------------------------------------------------------------------
// Question bank. Each option updates the candidate scores and/or patient state.
// `gain` marks how strongly the answer separates candidates.
// ---------------------------------------------------------------------------
const QUESTIONS = [
  {
    id: 'onset',
    field: 'onset',
    when: null,
    en: 'When did this start?',
    ar: 'متى بدأت الأعراض؟',
    why_en: 'How quickly something started changes how urgently it should be assessed.',
    why_ar: 'سرعة بدء الأعراض تغير مدى إلحاح التقييم.',
    options: [
      { v: 'minutes', en: 'Within the last hour', ar: 'خلال الساعة الماضية', urgency: 2, effects: { acs: 2, appendicitis: 1 } },
      { v: 'today', en: 'Today', ar: 'اليوم', urgency: 1, effects: { gastroenteritis: 1, acs: 1 } },
      { v: 'days', en: 'A few days ago', ar: 'قبل بضعة أيام', effects: { lower_resp_infection: 1, viral_uri: 1, uti: 1 } },
      { v: 'weeks', en: 'Weeks or longer', ar: 'أسابيع أو أكثر', effects: { anaemia_fatigue: 2, mechanical_back: 1, tension_headache: 1, acs: -1 } },
    ],
  },
  {
    id: 'severity',
    field: 'severity',
    when: null,
    en: 'How intense is it right now, from mild to severe?',
    ar: 'ما شدتها الآن، من خفيفة إلى شديدة؟',
    why_en: 'Intensity helps decide how soon you should be seen, separately from the cause.',
    why_ar: 'الشدة تساعد في تحديد سرعة الحاجة للتقييم، بمعزل عن السبب.',
    options: [
      { v: 'mild', en: 'Mild, I can carry on', ar: 'خفيفة، أستطيع المتابعة' },
      { v: 'moderate', en: 'Moderate, it distracts me', ar: 'متوسطة، تشتت انتباهي', urgency: 1 },
      { v: 'severe', en: 'Severe, I cannot function', ar: 'شديدة، لا أستطيع أداء مهامي', urgency: 2, effects: { acs: 1, appendicitis: 1 } },
    ],
  },
  {
    id: 'exertion',
    field: 'exertion_relation',
    when: ['chest_pain', 'breathlessness'],
    en: 'Does it come on with physical effort, or also while you are resting?',
    ar: 'هل تظهر مع المجهود البدني، أم أيضًا أثناء الراحة؟',
    why_en: 'Discomfort brought on by effort and eased by rest points towards the heart rather than the chest wall.',
    why_ar: 'الانزعاج الذي يظهر مع المجهود ويخف بالراحة يوجّه نحو القلب بدل جدار الصدر.',
    options: [
      { v: 'exertion', en: 'Mainly with effort, eases with rest', ar: 'غالبًا مع المجهود ويخف بالراحة', urgency: 2, effects: { acs: 3, musculoskeletal_chest: -2, anxiety_panic: -1 } },
      { v: 'rest', en: 'Also at rest', ar: 'حتى أثناء الراحة', urgency: 1, effects: { acs: 1, anxiety_panic: 1, reflux: 1 } },
      { v: 'movement', en: 'Only when I move or twist', ar: 'فقط عند الحركة أو الالتفاف', effects: { musculoskeletal_chest: 3, acs: -2 } },
    ],
  },
  {
    id: 'radiation',
    field: 'radiation',
    when: ['chest_pain'],
    en: 'Does the discomfort spread anywhere, such as the arm, jaw, neck or back?',
    ar: 'هل ينتشر الانزعاج إلى مكان آخر مثل الذراع أو الفك أو الرقبة أو الظهر؟',
    why_en: 'Pain spreading to the arm or jaw is one of the findings clinicians weigh most heavily in chest pain.',
    why_ar: 'انتشار الألم إلى الذراع أو الفك من أكثر العلامات التي يعتمد عليها الأطباء في ألم الصدر.',
    options: [
      { v: 'arm_jaw', en: 'Yes, to the arm, jaw or neck', ar: 'نعم، إلى الذراع أو الفك أو الرقبة', urgency: 3, flag: 'acute_coronary', effects: { acs: 3, musculoskeletal_chest: -2 } },
      { v: 'back', en: 'Yes, through to the back', ar: 'نعم، إلى الظهر', urgency: 2, effects: { acs: 1 } },
      { v: 'no', en: 'No, it stays in one place', ar: 'لا، يبقى في مكان واحد', effects: { musculoskeletal_chest: 2, reflux: 1 } },
    ],
  },
  {
    id: 'press_chest',
    field: 'reproducible',
    when: ['chest_pain'],
    en: 'If you press on the sore spot, does the same pain come back?',
    ar: 'إذا ضغطتِ على المكان المؤلم، هل يعود نفس الألم؟',
    why_en: 'Pain reproduced by pressing usually comes from the chest wall rather than an internal organ.',
    why_ar: 'الألم الذي يعود بالضغط ينشأ عادة من جدار الصدر وليس من عضو داخلي.',
    options: [
      { v: 'yes', en: 'Yes, pressing reproduces it', ar: 'نعم، الضغط يعيده', effects: { musculoskeletal_chest: 3, acs: -2 } },
      { v: 'no', en: 'No, pressing changes nothing', ar: 'لا، الضغط لا يغير شيئًا', effects: { acs: 1, reflux: 1 } },
    ],
  },
  {
    id: 'meals',
    field: 'meal_relation',
    when: ['chest_pain', 'abdominal_pain', 'nausea'],
    en: 'Is it linked to meals or to lying down?',
    ar: 'هل لها علاقة بالوجبات أو بالاستلقاء؟',
    why_en: 'A link to meals or lying flat shifts weight towards a digestive explanation.',
    why_ar: 'الارتباط بالوجبات أو الاستلقاء يرجّح التفسير الهضمي.',
    options: [
      { v: 'yes', en: 'Yes, worse after eating or lying flat', ar: 'نعم، تسوء بعد الأكل أو الاستلقاء', effects: { reflux: 3, acs: -1 } },
      { v: 'no', en: 'No clear link', ar: 'لا يوجد ارتباط واضح', effects: { reflux: -1 } },
    ],
  },
  {
    id: 'breath_effort',
    field: 'breathing',
    when: ['breathlessness'],
    en: 'Are you breathless while sitting still, or only when active?',
    ar: 'هل يوجد ضيق نفس وأنتِ جالسة دون حراك، أم فقط عند النشاط؟',
    why_en: 'Breathlessness at rest raises urgency regardless of the underlying cause.',
    why_ar: 'ضيق النفس أثناء الراحة يرفع درجة الإلحاح بغض النظر عن السبب.',
    options: [
      { v: 'rest', en: 'At rest', ar: 'أثناء الراحة', urgency: 3, effects: { acs: 2, lower_resp_infection: 2 } },
      { v: 'activity', en: 'Only when active', ar: 'فقط عند النشاط', urgency: 1, effects: { acs: 1, anaemia_fatigue: 1 } },
      { v: 'episodes', en: 'In short episodes with stress', ar: 'في نوبات قصيرة مع التوتر', effects: { anxiety_panic: 3 } },
    ],
  },
  {
    id: 'fever_level',
    field: 'fever',
    when: ['fever', 'cough', 'sore_throat', 'abdominal_pain', 'urinary'],
    en: 'Have you measured a temperature above 38C?',
    ar: 'هل قِسْتِ حرارة أعلى من 38 درجة؟',
    why_en: 'A measured fever changes both the shortlist and how soon assessment is advised.',
    why_ar: 'الحرارة المقاسة تغير قائمة الاحتمالات وسرعة التقييم الموصى به.',
    options: [
      { v: 'yes', en: 'Yes', ar: 'نعم', urgency: 1, effects: { lower_resp_infection: 2, uti: 2, appendicitis: 2, viral_uri: 1, migraine: -1 } },
      { v: 'no', en: 'No', ar: 'لا', effects: { lower_resp_infection: -1, appendicitis: -1 } },
      { v: 'unmeasured', en: 'I feel hot but have not measured', ar: 'أشعر بحرارة لكن لم أقِس', effects: { viral_uri: 1 } },
    ],
  },
  {
    id: 'headache_character',
    field: 'headache_character',
    when: ['headache'],
    en: 'Is the headache on one side and throbbing, or a band of pressure around the head?',
    ar: 'هل الصداع في جهة واحدة ونابض، أم ضغط كالشريط حول الرأس؟',
    why_en: 'Side and quality are the main features that separate migraine from tension-type headache.',
    why_ar: 'الجهة والطابع هما أهم ما يفرق بين الشقيقة والصداع التوتري.',
    options: [
      { v: 'one_throb', en: 'One side, throbbing', ar: 'جهة واحدة، نابض', effects: { migraine: 3, tension_headache: -2 } },
      { v: 'band', en: 'Pressure on both sides', ar: 'ضغط في الجهتين', effects: { tension_headache: 3, migraine: -1 } },
      { v: 'sudden', en: 'It hit maximum intensity within seconds', ar: 'وصل لأقصى شدة خلال ثوانٍ', urgency: 3, flag: 'thunderclap_headache' },
    ],
  },
  {
    id: 'light_sound',
    field: 'photophobia',
    when: ['headache'],
    en: 'Do light and sound make it noticeably worse?',
    ar: 'هل يزداد الألم بوضوح مع الضوء والصوت؟',
    why_en: 'Sensitivity to light and sound is one of the strongest separators between headache types.',
    why_ar: 'الحساسية للضوء والصوت من أقوى ما يفرق بين أنواع الصداع.',
    options: [
      { v: 'yes', en: 'Yes', ar: 'نعم', effects: { migraine: 3, tension_headache: -2 } },
      { v: 'no', en: 'No', ar: 'لا', effects: { tension_headache: 2, migraine: -1 } },
    ],
  },
  {
    id: 'abdo_location',
    field: 'abdo_location',
    when: ['abdominal_pain'],
    en: 'Where is the pain now, and has it moved since it began?',
    ar: 'أين الألم الآن، وهل انتقل منذ أن بدأ؟',
    why_en: 'Pain that starts centrally and settles in the lower right abdomen is assessed surgically without delay.',
    why_ar: 'الألم الذي يبدأ وسط البطن ويستقر أسفل اليمين يُقيَّم جراحيًا دون تأخير.',
    options: [
      { v: 'moved_rlq', en: 'It moved to the lower right', ar: 'انتقل إلى أسفل اليمين', urgency: 3, effects: { appendicitis: 4, gastroenteritis: -2 } },
      { v: 'upper', en: 'Upper abdomen', ar: 'أعلى البطن', effects: { reflux: 2 } },
      { v: 'lower', en: 'Lower abdomen, both sides', ar: 'أسفل البطن، الجهتان', effects: { uti: 2, gastroenteritis: 1 } },
      { v: 'general', en: 'All over, cramping', ar: 'في كل البطن، تقلصات', effects: { gastroenteritis: 2 } },
    ],
  },
  {
    id: 'urinary_burning',
    field: 'urinary_burning',
    when: ['urinary', 'abdominal_pain', 'back_pain'],
    en: 'Is there burning when you pass urine, or a need to go much more often?',
    ar: 'هل يوجد حرقان عند التبول أو حاجة للتبول أكثر بكثير؟',
    why_en: 'These two features carry most of the weight in assessing a urinary infection.',
    why_ar: 'هاتان العلامتان تحملان معظم الوزن في تقييم التهاب المسالك البولية.',
    options: [
      { v: 'yes', en: 'Yes', ar: 'نعم', effects: { uti: 3 } },
      { v: 'no', en: 'No', ar: 'لا', effects: { uti: -2 } },
    ],
  },
  {
    id: 'back_radiation',
    field: 'back_radiation',
    when: ['back_pain'],
    en: 'Does the pain travel down the leg, below the knee?',
    ar: 'هل ينتشر الألم إلى الساق أسفل الركبة؟',
    why_en: 'Pain below the knee suggests nerve involvement, which changes the examination a clinician performs.',
    why_ar: 'انتشار الألم أسفل الركبة يشير إلى تأثر عصبي، مما يغير الفحص الذي يجريه الطبيب.',
    options: [
      { v: 'yes', en: 'Yes, past the knee', ar: 'نعم، إلى ما بعد الركبة', urgency: 1, effects: { mechanical_back: 1 } },
      { v: 'no', en: 'No, it stays in the back', ar: 'لا، يبقى في الظهر', effects: { mechanical_back: 2 } },
    ],
  },
  {
    id: 'rash_pressure',
    field: 'rash_blanching',
    when: ['rash'],
    en: 'If you press a glass against the rash, does it fade?',
    ar: 'إذا ضغطتِ كوبًا زجاجيًا على الطفح، هل يبهت لونه؟',
    why_en: 'A rash that does not fade under pressure is assessed urgently.',
    why_ar: 'الطفح الذي لا يبهت تحت الضغط يُقيَّم بشكل عاجل.',
    options: [
      { v: 'fades', en: 'Yes, it fades', ar: 'نعم، يبهت', effects: { allergic_reaction: 2 } },
      { v: 'stays', en: 'No, it stays visible', ar: 'لا، يبقى ظاهرًا', urgency: 3, flag: 'sepsis' },
    ],
  },
  {
    id: 'duration_fatigue',
    field: 'fatigue_duration',
    when: ['fatigue'],
    en: 'How long has the tiredness been present?',
    ar: 'منذ متى وأنتِ تشعرين بالتعب؟',
    why_en: 'Tiredness lasting more than a few weeks is usually investigated with blood tests.',
    why_ar: 'التعب المستمر أكثر من بضعة أسابيع يُفحص عادة بتحاليل دم.',
    options: [
      { v: 'short', en: 'Under two weeks', ar: 'أقل من أسبوعين', effects: { viral_uri: 1 } },
      { v: 'long', en: 'More than a month', ar: 'أكثر من شهر', effects: { anaemia_fatigue: 3 } },
    ],
  },
  {
    id: 'inhaler_response',
    field: 'inhaler_response',
    when: ['wheeze', 'breathlessness', 'cough'],
    en: 'Do you use an inhaler, and does it help when this happens?',
    ar: 'هل تستخدمين بخاخًا، وهل يساعد عند حدوث ذلك؟',
    why_en: 'A response to an inhaler separates airway narrowing from other causes of breathlessness.',
    why_ar: 'الاستجابة للبخاخ تفرق بين ضيق المجاري الهوائية وأسباب أخرى لضيق النفس.',
    options: [
      { v: 'helps', en: 'Yes, and it helps', ar: 'نعم، ويساعد', effects: { asthma_flare: 3, acs: -1 } },
      { v: 'not_helping', en: 'Yes, but it is not helping now', ar: 'نعم، لكنه لا يساعد الآن', urgency: 3, flag: 'severe_asthma', effects: { asthma_flare: 2 } },
      { v: 'none', en: 'I do not use one', ar: 'لا أستخدم بخاخًا', effects: { asthma_flare: -1 } },
    ],
  },
  {
    id: 'leg_side',
    field: 'leg_side',
    when: ['leg_swelling'],
    en: 'Is the swelling in one leg or both?',
    ar: 'هل التورم في ساق واحدة أم في الاثنتين؟',
    why_en: 'Swelling in one leg is assessed differently from swelling in both, because a clot affects one side.',
    why_ar: 'تورم ساق واحدة يُقيَّم بشكل مختلف عن تورم الاثنتين، لأن الجلطة تصيب جهة واحدة.',
    options: [
      { v: 'one', en: 'One leg', ar: 'ساق واحدة', urgency: 3, effects: { venous_thrombosis: 3, cellulitis: 1 } },
      { v: 'both', en: 'Both legs', ar: 'الساقان', effects: { venous_thrombosis: -2 } },
    ],
  },
  {
    id: 'travel_immobility',
    field: 'immobility',
    when: ['leg_swelling', 'breathlessness'],
    en: 'Have you had surgery, a long journey, or several days of limited movement recently?',
    ar: 'هل خضعتِ لجراحة أو سافرتِ مسافة طويلة أو قلّت حركتك لعدة أيام مؤخرًا؟',
    why_en: 'Immobility is one of the strongest pieces of context in assessing a possible clot.',
    why_ar: 'قلة الحركة من أقوى عناصر السياق في تقييم احتمال الجلطة.',
    options: [
      { v: 'yes', en: 'Yes', ar: 'نعم', urgency: 2, effects: { venous_thrombosis: 3 } },
      { v: 'no', en: 'No', ar: 'لا', effects: { venous_thrombosis: -1 } },
    ],
  },
  {
    id: 'eye_vision',
    field: 'eye_vision',
    when: ['eye_redness'],
    en: 'Is your vision affected in that eye?',
    ar: 'هل تأثرت الرؤية في تلك العين؟',
    why_en: 'A red eye with normal vision is usually a surface problem; changed vision is assessed urgently.',
    why_ar: 'العين الحمراء مع رؤية طبيعية مشكلة سطحية عادة؛ أما تغير الرؤية فيُقيَّم بشكل عاجل.',
    options: [
      { v: 'normal', en: 'No, vision is normal', ar: 'لا، الرؤية طبيعية', effects: { conjunctivitis: 3 } },
      { v: 'affected', en: 'Yes, vision has changed', ar: 'نعم، تغيرت الرؤية', urgency: 3, flag: 'acute_vision_loss', effects: { conjunctivitis: -2 } },
    ],
  },
  {
    id: 'thirst_duration',
    field: 'thirst_duration',
    when: ['thirst', 'fatigue', 'weight_loss'],
    en: 'Have you been unusually thirsty, or passing urine more at night, for weeks?',
    ar: 'هل تشعرين بعطش غير معتاد أو تبول أكثر ليلًا منذ أسابيع؟',
    why_en: 'Thirst with night-time urination over weeks is the pattern that prompts a blood sugar test.',
    why_ar: 'العطش مع التبول الليلي عبر أسابيع هو النمط الذي يستدعي فحص سكر الدم.',
    options: [
      { v: 'yes', en: 'Yes', ar: 'نعم', urgency: 1, effects: { hyperglycaemia: 3 } },
      { v: 'no', en: 'No', ar: 'لا', effects: { hyperglycaemia: -2 } },
    ],
  },
  {
    id: 'vertigo_trigger',
    field: 'vertigo_trigger',
    when: ['vertigo_spin', 'dizziness'],
    en: 'Does turning your head or rolling over in bed set it off?',
    ar: 'هل يبدأ الدوار عند تحريك رأسك أو التقلب في السرير؟',
    why_en: 'Position-triggered spinning points to the inner ear rather than to blood pressure or the brain.',
    why_ar: 'الدوران الذي تثيره الوضعية يشير إلى الأذن الداخلية لا إلى الضغط أو الدماغ.',
    options: [
      { v: 'yes', en: 'Yes, position sets it off', ar: 'نعم، الوضعية تثيره', effects: { bppv_vertigo: 3, dehydration: -1 } },
      { v: 'standing', en: 'Only when I stand up', ar: 'فقط عند الوقوف', effects: { dehydration: 3, bppv_vertigo: -1 } },
      { v: 'no', en: 'No clear trigger', ar: 'لا يوجد محفز واضح', effects: {} },
    ],
  },
  {
    id: 'travel_exposure',
    field: 'travel',
    when: ['fever', 'joint_pain', 'headache'],
    en: 'Have you travelled recently, or are you in an area where malaria or dengue occur?',
    ar: 'هل سافرتِ مؤخرًا أو أنتِ في منطقة تنتشر فيها الملاريا أو حمى الضنك؟',
    why_en: 'Travel and mosquito exposure change which febrile illnesses are considered and how fast.',
    why_ar: 'السفر والتعرض للبعوض يغيران الأمراض الحموية التي تُؤخذ في الحسبان وسرعة ذلك.',
    options: [
      { v: 'yes', en: 'Yes', ar: 'نعم', urgency: 2, effects: { febrile_illness: 3 } },
      { v: 'no', en: 'No', ar: 'لا', effects: { febrile_illness: -1 } },
    ],
  },
  {
    id: 'skin_spread',
    field: 'skin_spread',
    when: ['skin_infection', 'rash'],
    en: 'Is the red area spreading, and does it feel hot to touch?',
    ar: 'هل تتسع المنطقة الحمراء وهل تشعرين بسخونتها عند اللمس؟',
    why_en: 'A spreading, hot edge with fever is treated differently from an itchy allergic rash.',
    why_ar: 'الحافة الساخنة المتسعة مع الحمى تُعالج بشكل مختلف عن الطفح التحسسي الحاك.',
    options: [
      { v: 'spreading', en: 'Yes, spreading and hot', ar: 'نعم، تتسع وساخنة', urgency: 2, effects: { cellulitis: 3, allergic_reaction: -2 } },
      { v: 'itchy', en: 'No, it is mainly itchy', ar: 'لا، حاكة بشكل أساسي', effects: { allergic_reaction: 3, cellulitis: -2 } },
    ],
  },
  {
    id: 'meds',
    field: 'medications',
    when: null,
    en: 'Are you taking any regular medicines?',
    ar: 'هل تتناولين أدوية بشكل منتظم؟',
    why_en: 'Medicines change both what is likely and what is safe to suggest.',
    why_ar: 'الأدوية تغير الاحتمالات وما يمكن اقتراحه بأمان.',
    options: [
      { v: 'none', en: 'None', ar: 'لا شيء' },
      { v: 'some', en: 'Yes, one or more', ar: 'نعم، دواء أو أكثر' },
      { v: 'new', en: 'Yes, and one was started recently', ar: 'نعم، وبدأت واحدًا مؤخرًا', effects: { allergic_reaction: 2 } },
    ],
  },
  {
    id: 'history',
    field: 'history',
    when: null,
    en: 'Do you have any ongoing health conditions?',
    ar: 'هل لديك حالات صحية مزمنة؟',
    why_en: 'Existing conditions change which explanations are plausible and how urgently to act.',
    why_ar: 'الحالات الموجودة تغير الاحتمالات المنطقية ومدى الإلحاح.',
    options: [
      { v: 'none', en: 'None that I know of', ar: 'لا أعلم بوجود شيء' },
      { v: 'cardiac', en: 'Heart or blood pressure', ar: 'قلب أو ضغط', urgency: 1, effects: { acs: 2 } },
      { v: 'diabetes', en: 'Diabetes', ar: 'سكري', urgency: 1, effects: { acs: 1, uti: 1 } },
      { v: 'respiratory', en: 'Asthma or lung condition', ar: 'ربو أو مرض رئوي', effects: { lower_resp_infection: 2 } },
      { v: 'other', en: 'Something else', ar: 'شيء آخر' },
    ],
  },
];

const CONDITION_BY_ID = Object.fromEntries(CONDITIONS.map((c) => [c.id, c]));

module.exports = { SOURCES, SYMPTOMS, RED_FLAGS, CONDITIONS, CONDITION_BY_ID, QUESTIONS };
