-- Seed for migration 003, generated from src/clinical/evaluations.js.

insert into clinical_evaluations (id, eval_type, name_en, name_ar, why_en, why_ar, question_en, question_ar, expect_en, expect_ar, preparation_en, preparation_ar, safety_relevant) values
  ('ecg', 'bedside test', 'Electrical tracing of the heart (ECG)', 'تخطيط كهربية القلب', 'Chest symptoms that may involve the heart are usually assessed with an electrical tracing first, because it is quick and available at the bedside.', 'تُقيَّم أعراض الصدر التي قد تتعلق بالقلب عادة بتخطيط كهربائي أولًا، لأنه سريع ومتاح عند السرير.', 'May help evaluate whether the heart muscle is under strain at the time of the recording.', 'قد يساعد في تقييم ما إذا كانت عضلة القلب تحت إجهاد وقت التسجيل.', 'Small stickers are placed on the chest, arms and legs for a few minutes. It records only; nothing is passed into the body.', 'تُوضع لواصق صغيرة على الصدر والذراعين والساقين لبضع دقائق. وهو يسجّل فقط ولا يُمرَّر شيء إلى الجسم.', null, null, true),
  ('cardiac_bloods', 'laboratory', 'Blood test for cardiac markers', 'تحليل دم لمؤشرات القلب', 'Blood markers change when heart muscle is injured, so a clinician may use them alongside the tracing and the history.', 'تتغير مؤشرات الدم عند إصابة عضلة القلب، وقد يستخدمها الطبيب إلى جانب التخطيط والتاريخ المرضي.', 'May help distinguish a cardiac cause of chest discomfort from a chest wall or digestive cause.', 'قد يساعد في التفريق بين سبب قلبي لانزعاج الصدر وسبب في جدار الصدر أو في الجهاز الهضمي.', 'A blood sample, sometimes repeated a few hours later.', 'عينة دم، وقد تُعاد بعد بضع ساعات.', null, null, true),
  ('chest_xray', 'imaging', 'Chest X-ray', 'أشعة سينية للصدر', 'Cough, fever and breathlessness together sometimes lead a clinician to look at the lungs.', 'قد يدفع اجتماع السعال والحمى وضيق النفس الطبيب إلى النظر في الرئتين.', 'May help evaluate whether there is a change in the lungs that would explain the breathing symptoms.', 'قد يساعد في تقييم وجود تغير في الرئتين يفسر أعراض التنفس.', 'A brief X-ray, usually standing, taking a few seconds.', 'صورة أشعة قصيرة، غالبًا في وضع الوقوف، تستغرق ثوانٍ.', 'Tell the team if you are pregnant or might be, before any X-ray.', 'أخبري الفريق الطبي إن كنتِ حاملًا أو يُحتمل ذلك، قبل أي أشعة.', true),
  ('oxygen_saturation', 'bedside test', 'Oxygen level and breathing rate', 'قياس الأكسجين ومعدل التنفس', 'How much oxygen is in the blood, and how fast someone is breathing, changes how urgently a breathing problem is treated.', 'مستوى الأكسجين في الدم وسرعة التنفس يغيران مدى إلحاح التعامل مع مشكلة التنفس.', 'May help evaluate how well the lungs are moving oxygen right now.', 'قد يساعد في تقييم كفاءة الرئتين في نقل الأكسجين في الوقت الحالي.', 'A clip on a fingertip for a few seconds.', 'مشبك على طرف الإصبع لبضع ثوانٍ.', 'Remove nail polish from one finger if you can.', 'أزيلي طلاء الأظافر عن إصبع واحد إن أمكن.', true),
  ('peak_flow', 'bedside test', 'Peak flow or breathing test', 'قياس ذروة الجريان أو وظائف التنفس', 'Measuring how hard air can be blown out gives a clinician a number to compare over time.', 'قياس قوة إخراج الهواء يعطي الطبيب رقمًا يمكن مقارنته عبر الوقت.', 'May help evaluate whether the airways are narrowed, and by how much.', 'قد يساعد في تقييم وجود ضيق في المجاري الهوائية ومقداره.', 'Blowing hard into a small tube two or three times.', 'النفخ بقوة في أنبوب صغير مرتين أو ثلاثًا.', null, null, false),
  ('full_blood_count', 'laboratory', 'Full blood count', 'صورة دم كاملة', 'Tiredness lasting weeks, or a fever without an obvious source, is commonly assessed with a simple blood count first.', 'التعب المستمر لأسابيع أو الحمى دون سبب واضح يُقيَّمان عادة بصورة دم بسيطة أولًا.', 'May help evaluate anaemia or a blood picture that suggests infection.', 'قد تساعد في تقييم فقر الدم أو صورة دم توحي بوجود عدوى.', 'One blood sample from the arm.', 'عينة دم واحدة من الذراع.', null, null, false),
  ('iron_thyroid', 'laboratory', 'Iron studies and thyroid function', 'تحاليل الحديد ووظائف الغدة الدرقية', 'When tiredness persists, a clinician often looks at iron stores and thyroid activity because both are common and treatable.', 'عند استمرار التعب ينظر الطبيب غالبًا في مخزون الحديد ونشاط الغدة الدرقية لأنهما شائعان وقابلان للعلاج.', 'May help distinguish iron deficiency from a thyroid cause of the same symptoms.', 'قد تساعد في التفريق بين نقص الحديد وسبب درقي لنفس الأعراض.', 'Usually taken from the same blood sample as the blood count.', 'تؤخذ عادة من نفس عينة الدم المستخدمة لصورة الدم.', null, null, false),
  ('blood_glucose', 'laboratory', 'Blood sugar and HbA1c', 'سكر الدم والسكر التراكمي', 'Thirst, passing urine often and weight loss together are the pattern that leads a clinician to check blood sugar.', 'العطش وكثرة التبول وفقدان الوزن معًا هي النمط الذي يدفع الطبيب لفحص سكر الدم.', 'May help evaluate whether blood sugar is raised, and how it has been over recent months.', 'قد يساعد في تقييم ارتفاع سكر الدم وكيف كان خلال الأشهر الماضية.', 'A finger-prick reading, a blood sample, or both.', 'قراءة بوخز الإصبع أو عينة دم أو كلاهما.', 'Ask the clinic whether the sample should be taken at a particular time of day. Do not change how you eat or take any medicine on your own before a test.', 'اسألي العيادة إن كان يجب أخذ العينة في وقت معين من اليوم. ولا تغيّري طعامك أو أدويتك من تلقاء نفسك قبل أي فحص.', true),
  ('urine_dipstick', 'laboratory', 'Urine test and culture', 'تحليل وزراعة بول', 'Burning on passing urine, or pain that may come from the kidney, is usually assessed with a urine sample.', 'الحرقان أثناء التبول أو ألم قد يأتي من الكلية يُقيَّم عادة بعينة بول.', 'May help distinguish a urinary infection from a stone or another cause of the same pain.', 'قد يساعد في التفريق بين التهاب المسالك والحصوة أو سبب آخر لنفس الألم.', 'A urine sample in a clean container; a result strip is often read immediately.', 'عينة بول في وعاء نظيف، وغالبًا تُقرأ شريحة النتيجة فورًا.', 'If you can, keep a urine sample rather than emptying your bladder just before the appointment.', 'إن أمكن، احتفظي بعينة بول بدل إفراغ المثانة قبل الموعد مباشرة.', false),
  ('abdominal_ultrasound', 'imaging', 'Abdominal ultrasound', 'موجات صوتية للبطن', 'Pain under the right ribs after fatty food often leads a clinician to look at the gallbladder.', 'الألم تحت الأضلاع اليمنى بعد الطعام الدسم يدفع الطبيب غالبًا للنظر في المرارة.', 'May help evaluate the gallbladder, the liver and the kidneys without radiation.', 'قد تساعد في تقييم المرارة والكبد والكلى دون إشعاع.', 'Gel on the skin and a probe moved across the abdomen. It is painless.', 'جل على الجلد ومسبار يُمرَّر على البطن. وهي غير مؤلمة.', 'The clinic will tell you whether any preparation is needed for your situation.', 'ستخبرك العيادة بما إذا كان هناك أي تحضير مطلوب في حالتك.', false),
  ('surgical_review', 'clinical examination', 'Assessment by a surgical team', 'تقييم من فريق جراحي', 'Abdominal pain that moves and becomes constant is assessed in person without delay, because the examination itself carries most of the information.', 'ألم البطن الذي ينتقل ويصبح مستمرًا يُقيَّم شخصيًا دون تأخير، لأن الفحص نفسه يحمل معظم المعلومات.', 'May help evaluate whether an urgent surgical cause is present.', 'قد يساعد في تقييم وجود سبب جراحي عاجل.', 'Examination of the abdomen, usually with blood tests and sometimes imaging.', 'فحص للبطن، عادة مع تحاليل دم وأحيانًا تصوير.', 'Do not eat or drink on the way in until the team has assessed you, in case a procedure is needed.', 'تجنبي الأكل والشرب في الطريق حتى يقيّمك الفريق، تحسبًا للحاجة إلى إجراء.', true),
  ('leg_ultrasound', 'imaging', 'Ultrasound of the leg veins', 'موجات صوتية لأوردة الساق', 'Swelling and pain in one calf, particularly after immobility, is assessed for a clot because a clot can travel to the lung.', 'تورم وألم في ساق واحدة، خاصة بعد قلة الحركة، يُقيَّم بحثًا عن جلطة لأنها قد تنتقل إلى الرئة.', 'May help evaluate whether blood is flowing normally through the deep veins of the leg.', 'قد تساعد في تقييم ما إذا كان الدم يتدفق بشكل طبيعي في الأوردة العميقة للساق.', 'A probe pressed gently along the leg for several minutes.', 'مسبار يُضغط برفق على طول الساق لعدة دقائق.', null, null, true),
  ('ct_urinary', 'imaging', 'CT scan of the urinary tract', 'أشعة مقطعية للمسالك البولية', 'When pain comes in waves from the flank towards the groin, a clinician may want to see whether a stone is present and where.', 'عندما يأتي الألم على موجات من الخاصرة نحو المنطقة الأربية، قد يرغب الطبيب في معرفة وجود حصوة وموقعها.', 'May help evaluate the size and position of a stone, which changes what is done next.', 'قد تساعد في تقييم حجم الحصوة وموقعها، وهو ما يغير الخطوة التالية.', 'Lying still on a scanner bed for a few minutes.', 'الاستلقاء دون حركة على سرير الجهاز لبضع دقائق.', 'Tell the team if you are pregnant or might be, and if you have had a reaction to contrast dye before.', 'أخبري الفريق إن كنتِ حاملًا أو يُحتمل ذلك، وإن سبق أن تفاعلتِ مع صبغة التباين.', false),
  ('h_pylori', 'laboratory', 'Test for stomach bacteria (H. pylori)', 'فحص جرثومة المعدة', 'Burning upper abdominal pain that changes with eating is often assessed for a common stomach bacterium.', 'ألم حارق أعلى البطن يتغير مع الأكل يُفحص غالبًا بحثًا عن جرثومة معدة شائعة.', 'May help evaluate one treatable contributor to ulcer-type pain.', 'قد يساعد في تقييم أحد الأسباب القابلة للعلاج لألم يشبه القرحة.', 'A breath, stool or blood test, depending on the clinic.', 'فحص نفس أو براز أو دم، حسب العيادة.', 'The clinic will tell you whether any preparation is needed for your situation.', 'ستخبرك العيادة بما إذا كان هناك أي تحضير مطلوب في حالتك.', false),
  ('endoscopy', 'procedure', 'Endoscopy of the upper digestive tract', 'منظار للجهاز الهضمي العلوي', 'A clinician considers looking directly at the stomach lining when warning features are present, not for ordinary reflux.', 'ينظر الطبيب في فحص بطانة المعدة مباشرة عند وجود علامات تحذيرية، لا في حالات الارتجاع الاعتيادية.', 'May help evaluate the lining of the food pipe and stomach directly.', 'قد يساعد في تقييم بطانة المريء والمعدة مباشرة.', 'A thin flexible camera is passed through the mouth, usually with sedation or a throat spray.', 'كاميرا رفيعة مرنة تمر عبر الفم، عادة مع مهدئ أو بخاخ للحلق.', 'The endoscopy unit gives its own instructions beforehand. Follow those rather than anything general, and tell them about every medicine you take.', 'تعطي وحدة المناظير تعليماتها الخاصة مسبقًا. اتبعيها بدل أي تعليمات عامة، وأخبريهم بكل دواء تتناولينه.', false),
  ('stool_test', 'laboratory', 'Stool testing', 'تحليل براز', 'Most short-lived gut infections settle without testing; a clinician considers it when symptoms last, or after travel, or when there is blood.', 'معظم التهابات الأمعاء القصيرة تزول دون فحص؛ وينظر فيه الطبيب عند استمرار الأعراض أو بعد السفر أو عند وجود دم.', 'May help evaluate which organism is involved when that changes the treatment.', 'قد يساعد في تحديد الكائن المسبب عندما يغير ذلك العلاج.', 'A small sample collected at home in a container from the clinic.', 'عينة صغيرة تُجمع في المنزل في وعاء من العيادة.', null, null, false),
  ('malaria_test', 'laboratory', 'Malaria and febrile illness testing', 'فحص الملاريا والأمراض الحموية', 'Fever with aching joints after travel, or in an area where malaria or dengue circulate, is tested early because timing matters.', 'الحمى مع آلام المفاصل بعد السفر، أو في منطقة تنتشر فيها الملاريا أو حمى الضنك، تُفحص مبكرًا لأن التوقيت مهم.', 'May help evaluate whether a mosquito-borne infection explains the fever.', 'قد يساعد في تقييم ما إذا كانت عدوى منقولة بالبعوض تفسر الحمى.', 'A blood sample, sometimes a rapid test read within minutes.', 'عينة دم، وأحيانًا فحص سريع تُقرأ نتيجته خلال دقائق.', 'Bring the dates and places of any recent travel.', 'أحضري تواريخ وأماكن أي سفر حديث.', true),
  ('ear_examination', 'clinical examination', 'Examination of the ear drum', 'فحص طبلة الأذن', 'Ear pain is assessed by looking at the ear drum, which usually settles the question without any test.', 'يُقيَّم ألم الأذن بالنظر إلى طبلة الأذن، وهو ما يحسم الأمر عادة دون أي فحص.', 'May help evaluate whether there is inflammation behind the ear drum.', 'قد يساعد في تقييم وجود التهاب خلف طبلة الأذن.', 'A lighted instrument held at the ear for a few seconds.', 'أداة مضيئة تُوضع عند الأذن لبضع ثوانٍ.', null, null, false),
  ('eye_examination', 'clinical examination', 'Eye examination including vision testing', 'فحص العين مع قياس الإبصار', 'A red eye with normal vision is usually a surface problem, so measuring vision is the step that separates the two.', 'العين الحمراء مع رؤية طبيعية تكون عادة مشكلة سطحية، لذا فإن قياس الإبصار هو ما يفصل بين الحالتين.', 'May help distinguish a surface irritation from a problem inside the eye.', 'قد يساعد في التفريق بين تهيج سطحي ومشكلة داخل العين.', 'Reading a chart, then examination with a light.', 'قراءة لوحة إبصار ثم فحص بالضوء.', 'Bring your glasses or lenses, and mention if you wear contact lenses.', 'أحضري نظارتك أو عدساتك، واذكري إن كنتِ تستخدمين عدسات لاصقة.', true),
  ('positional_testing', 'clinical examination', 'Positional testing for vertigo', 'اختبار وضعي للدوار', 'Moving the head in a specific way reproduces inner-ear vertigo, which is how a clinician tells it apart from other causes.', 'تحريك الرأس بطريقة معينة يعيد دوار الأذن الداخلية، وهو ما يميزه الطبيب به عن الأسباب الأخرى.', 'May help distinguish an inner-ear cause from a blood pressure or neurological cause.', 'قد يساعد في التفريق بين سبب من الأذن الداخلية وسبب متعلق بالضغط أو بالجهاز العصبي.', 'Lying back and turning the head under supervision; it can briefly bring on the spinning.', 'الاستلقاء وإدارة الرأس تحت إشراف، وقد يثير الدوران لفترة قصيرة.', 'Bring someone with you if the spinning makes travelling difficult.', 'اصطحبي شخصًا معك إذا كان الدوران يصعّب التنقل.', false),
  ('blood_pressure_lying_standing', 'bedside test', 'Blood pressure lying and standing', 'قياس الضغط أثناء الاستلقاء والوقوف', 'Light-headedness on standing is assessed by measuring the pressure in both positions, which takes a few minutes.', 'تُقيَّم الدوخة عند الوقوف بقياس الضغط في الوضعين، ويستغرق ذلك دقائق قليلة.', 'May help evaluate whether blood pressure drops on standing.', 'قد يساعد في تقييم انخفاض الضغط عند الوقوف.', 'A cuff on the arm, read twice with a short wait between.', 'حزام على الذراع، يُقرأ مرتين مع انتظار قصير بينهما.', null, null, false),
  ('headache_review', 'clinical examination', 'Headache history and neurological examination', 'تاريخ الصداع والفحص العصبي', 'Most headaches are diagnosed from the pattern and the examination. Imaging is considered only when warning features are present.', 'تُشخَّص معظم أنواع الصداع من النمط والفحص. ولا يُنظر في التصوير إلا عند وجود علامات تحذيرية.', 'May help distinguish migraine from tension-type headache and identify anything that needs further assessment.', 'قد يساعد في التفريق بين الشقيقة والصداع التوتري وتحديد ما يستدعي تقييمًا إضافيًا.', 'Questions about the pattern, then a short examination of vision, strength and balance.', 'أسئلة عن النمط ثم فحص قصير للرؤية والقوة والتوازن.', 'Note when the attacks happen, how long they last and what you took for them.', 'دوّني متى تحدث النوبات وكم تستمر وما الذي تناولتِه لها.', false),
  ('skin_review', 'clinical examination', 'Skin examination', 'فحص الجلد', 'A rash is usually assessed by looking at it, including whether the edge is spreading and whether it fades under pressure.', 'يُقيَّم الطفح عادة بالنظر إليه، بما في ذلك اتساع الحافة وما إذا كان يبهت تحت الضغط.', 'May help distinguish an allergic reaction from a spreading skin infection.', 'قد يساعد في التفريق بين تفاعل تحسسي والتهاب جلدي منتشر.', 'A look at the affected skin, sometimes with a mark drawn around the edge to track it.', 'نظرة على الجلد المصاب، وأحيانًا رسم خط حول الحافة لمتابعتها.', 'Photograph the rash when it is at its worst, and bring the names of anything new you took or used.', 'صوّري الطفح في أشد حالاته، وأحضري أسماء أي شيء جديد تناولتِه أو استخدمتِه.', true),
  ('back_examination', 'clinical examination', 'Back and leg examination', 'فحص الظهر والساق', 'Most back pain does not need imaging. The examination establishes whether a nerve is involved, which is what changes the plan.', 'معظم آلام الظهر لا تحتاج تصويرًا. والفحص يحدد وجود تأثر عصبي، وهو ما يغير الخطة.', 'May help evaluate whether a nerve root is involved rather than muscle and joint alone.', 'قد يساعد في تقييم تأثر جذر عصبي بدل العضلات والمفاصل وحدها.', 'Movement, reflexes and leg strength are checked.', 'يُفحص المدى الحركي وردود الأفعال وقوة الساق.', 'Wear clothing that allows the back and legs to be examined easily.', 'ارتدي ملابس تسمح بفحص الظهر والساقين بسهولة.', false),
  ('throat_swab', 'laboratory', 'Throat swab', 'مسحة حلق', 'Most sore throats are viral and need no test. A clinician considers a swab only in selected cases.', 'معظم حالات التهاب الحلق فيروسية ولا تحتاج فحصًا. ولا ينظر الطبيب في المسحة إلا في حالات مختارة.', 'May help evaluate whether a bacterial cause is present when the pattern suggests it.', 'قد تساعد في تقييم وجود سبب بكتيري عندما يوحي النمط بذلك.', 'A swab at the back of the throat, over in a second.', 'مسحة في مؤخرة الحلق تنتهي خلال ثانية.', null, null, false)
on conflict (id) do nothing;

insert into clinical_evaluation_links (evaluation_id, condition_id) values
  ('ecg', 'acs'),
  ('ecg', 'anxiety_panic'),
  ('ecg', 'venous_thrombosis'),
  ('cardiac_bloods', 'acs'),
  ('cardiac_bloods', 'musculoskeletal_chest'),
  ('cardiac_bloods', 'reflux'),
  ('chest_xray', 'lower_resp_infection'),
  ('chest_xray', 'asthma_flare'),
  ('chest_xray', 'acs'),
  ('oxygen_saturation', 'lower_resp_infection'),
  ('oxygen_saturation', 'asthma_flare'),
  ('oxygen_saturation', 'venous_thrombosis'),
  ('oxygen_saturation', 'acs'),
  ('peak_flow', 'asthma_flare'),
  ('peak_flow', 'lower_resp_infection'),
  ('full_blood_count', 'anaemia_fatigue'),
  ('full_blood_count', 'febrile_illness'),
  ('full_blood_count', 'lower_resp_infection'),
  ('full_blood_count', 'cellulitis'),
  ('full_blood_count', 'appendicitis'),
  ('iron_thyroid', 'anaemia_fatigue'),
  ('iron_thyroid', 'thyroid'),
  ('blood_glucose', 'hyperglycaemia'),
  ('urine_dipstick', 'uti'),
  ('urine_dipstick', 'renal_colic'),
  ('abdominal_ultrasound', 'biliary_colic'),
  ('abdominal_ultrasound', 'appendicitis'),
  ('abdominal_ultrasound', 'renal_colic'),
  ('surgical_review', 'appendicitis'),
  ('surgical_review', 'testicular_or_ectopic_pain'),
  ('surgical_review', 'biliary_colic'),
  ('leg_ultrasound', 'venous_thrombosis'),
  ('leg_ultrasound', 'cellulitis'),
  ('ct_urinary', 'renal_colic'),
  ('h_pylori', 'peptic_ulcer'),
  ('h_pylori', 'reflux'),
  ('endoscopy', 'peptic_ulcer'),
  ('endoscopy', 'reflux'),
  ('stool_test', 'gastroenteritis'),
  ('stool_test', 'febrile_illness'),
  ('malaria_test', 'febrile_illness'),
  ('ear_examination', 'otitis'),
  ('eye_examination', 'conjunctivitis'),
  ('positional_testing', 'bppv_vertigo'),
  ('positional_testing', 'dehydration'),
  ('blood_pressure_lying_standing', 'dehydration'),
  ('blood_pressure_lying_standing', 'anaemia_fatigue'),
  ('headache_review', 'migraine'),
  ('headache_review', 'tension_headache'),
  ('headache_review', 'sinusitis'),
  ('skin_review', 'allergic_reaction'),
  ('skin_review', 'cellulitis'),
  ('back_examination', 'mechanical_back'),
  ('throat_swab', 'viral_uri')
on conflict do nothing;

insert into clinical_evaluation_evidence (evaluation_id, source_id) values
  ('ecg', 'nice_chest_pain'),
  ('cardiac_bloods', 'nice_chest_pain'),
  ('chest_xray', 'nhs_conditions'),
  ('chest_xray', 'nice_sepsis'),
  ('oxygen_saturation', 'nice_sepsis'),
  ('peak_flow', 'nhs_conditions'),
  ('full_blood_count', 'medlineplus'),
  ('iron_thyroid', 'medlineplus'),
  ('blood_glucose', 'medlineplus'),
  ('urine_dipstick', 'nhs_conditions'),
  ('abdominal_ultrasound', 'nhs_conditions'),
  ('surgical_review', 'nhs_conditions'),
  ('leg_ultrasound', 'nhs_conditions'),
  ('ct_urinary', 'nhs_conditions'),
  ('h_pylori', 'nhs_conditions'),
  ('endoscopy', 'nhs_conditions'),
  ('stool_test', 'nhs_conditions'),
  ('malaria_test', 'who_ai_health'),
  ('malaria_test', 'nhs_conditions'),
  ('ear_examination', 'nhs_conditions'),
  ('eye_examination', 'nhs_conditions'),
  ('positional_testing', 'nhs_conditions'),
  ('blood_pressure_lying_standing', 'medlineplus'),
  ('headache_review', 'nice_headache'),
  ('skin_review', 'nhs_conditions'),
  ('back_examination', 'nice_low_back'),
  ('throat_swab', 'nhs_conditions')
on conflict do nothing;
